/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type sseEndpointApiV1NotificationsSseGetResponse200 = {
  data: unknown
  status: 200
}

export type sseEndpointApiV1NotificationsSseGetResponseSuccess = (sseEndpointApiV1NotificationsSseGetResponse200) & {
  headers: Headers;
};
;

export type sseEndpointApiV1NotificationsSseGetResponse = (sseEndpointApiV1NotificationsSseGetResponseSuccess)

export const getSseEndpointApiV1NotificationsSseGetUrl = () => {




  return `/api/v1/notifications/sse`
}

/**
 * Server-Sent Events endpoint for real-time notifications.
 * @summary Sse Endpoint
 */
export const sseEndpointApiV1NotificationsSseGet = async ( options?: RequestInit): Promise<sseEndpointApiV1NotificationsSseGetResponse> => {

  return customInstance<sseEndpointApiV1NotificationsSseGetResponse>(getSseEndpointApiV1NotificationsSseGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSseEndpointApiV1NotificationsSseGetQueryKey = () => {
    return [
    `/api/v1/notifications/sse`
    ] as const;
    }


export const getSseEndpointApiV1NotificationsSseGetQueryOptions = <TData = Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSseEndpointApiV1NotificationsSseGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>> = ({ signal }) => sseEndpointApiV1NotificationsSseGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SseEndpointApiV1NotificationsSseGetQueryResult = NonNullable<Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>>
export type SseEndpointApiV1NotificationsSseGetQueryError = unknown


export function useSseEndpointApiV1NotificationsSseGet<TData = Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>,
          TError,
          Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSseEndpointApiV1NotificationsSseGet<TData = Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>,
          TError,
          Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSseEndpointApiV1NotificationsSseGet<TData = Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Sse Endpoint
 */

export function useSseEndpointApiV1NotificationsSseGet<TData = Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sseEndpointApiV1NotificationsSseGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSseEndpointApiV1NotificationsSseGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getNotificationsApiV1NotificationsGetResponse200 = {
  data: unknown
  status: 200
}

export type getNotificationsApiV1NotificationsGetResponseSuccess = (getNotificationsApiV1NotificationsGetResponse200) & {
  headers: Headers;
};
;

export type getNotificationsApiV1NotificationsGetResponse = (getNotificationsApiV1NotificationsGetResponseSuccess)

export const getGetNotificationsApiV1NotificationsGetUrl = () => {




  return `/api/v1/notifications`
}

/**
 * Get all notifications for the current tenant and user.
 * @summary Get Notifications
 */
export const getNotificationsApiV1NotificationsGet = async ( options?: RequestInit): Promise<getNotificationsApiV1NotificationsGetResponse> => {

  return customInstance<getNotificationsApiV1NotificationsGetResponse>(getGetNotificationsApiV1NotificationsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetNotificationsApiV1NotificationsGetQueryKey = () => {
    return [
    `/api/v1/notifications`
    ] as const;
    }


export const getGetNotificationsApiV1NotificationsGetQueryOptions = <TData = Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotificationsApiV1NotificationsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>> = ({ signal }) => getNotificationsApiV1NotificationsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNotificationsApiV1NotificationsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>>
export type GetNotificationsApiV1NotificationsGetQueryError = unknown


export function useGetNotificationsApiV1NotificationsGet<TData = Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>,
          TError,
          Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotificationsApiV1NotificationsGet<TData = Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>,
          TError,
          Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotificationsApiV1NotificationsGet<TData = Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Notifications
 */

export function useGetNotificationsApiV1NotificationsGet<TData = Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNotificationsApiV1NotificationsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






