/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CorrectReviewRequest,
  HTTPValidationError,
  ListReviewsParams,
  RejectReviewRequest,
  ReviewContextResponse,
  ReviewItemResponse,
  ReviewMutationRequest,
  ReviewMutationResponse
} from '../../models';

import { customInstance } from '../../../lib/api/client';
import type { ErrorType , BodyType } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List Draft Reviews
 */
export const listReviews = (
    params?: ListReviewsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewItemResponse[]>(
      {url: `/api/v1/reviews`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListReviewsQueryKey = (params?: ListReviewsParams,) => {
    return [
    `/api/v1/reviews`, ...(params ? [params] : [])
    ] as const;
    }


export const getListReviewsQueryOptions = <TData = Awaited<ReturnType<typeof listReviews>>, TError = ErrorType<HTTPValidationError>>(params?: ListReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReviewsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReviews>>> = ({ signal }) => listReviews(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReviewsQueryResult = NonNullable<Awaited<ReturnType<typeof listReviews>>>
export type ListReviewsQueryError = ErrorType<HTTPValidationError>


export function useListReviews<TData = Awaited<ReturnType<typeof listReviews>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListReviewsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReviews>>,
          TError,
          Awaited<ReturnType<typeof listReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReviews<TData = Awaited<ReturnType<typeof listReviews>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReviews>>,
          TError,
          Awaited<ReturnType<typeof listReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReviews<TData = Awaited<ReturnType<typeof listReviews>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Draft Reviews
 */

export function useListReviews<TData = Awaited<ReturnType<typeof listReviews>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListReviewsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Approve Review
 */
export const approveReview = (
    reviewId: string,
    reviewMutationRequest: BodyType<ReviewMutationRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewMutationResponse>(
      {url: `/api/v1/reviews/${reviewId}/approve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reviewMutationRequest, signal
    },
      options);
    }




export const getApproveReviewMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveReview>>, TError,{reviewId: string;data: BodyType<ReviewMutationRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof approveReview>>, TError,{reviewId: string;data: BodyType<ReviewMutationRequest>}, TContext> => {

const mutationKey = ['approveReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveReview>>, {reviewId: string;data: BodyType<ReviewMutationRequest>}> = (props) => {
          const {reviewId,data} = props ?? {};

          return  approveReview(reviewId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApproveReviewMutationResult = NonNullable<Awaited<ReturnType<typeof approveReview>>>
    export type ApproveReviewMutationBody = BodyType<ReviewMutationRequest>
    export type ApproveReviewMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Approve Review
 */
export const useApproveReview = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveReview>>, TError,{reviewId: string;data: BodyType<ReviewMutationRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approveReview>>,
        TError,
        {reviewId: string;data: BodyType<ReviewMutationRequest>},
        TContext
      > => {
      return useMutation(getApproveReviewMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Review Context
 */
export const getReviewContext = (
    reviewId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewContextResponse>(
      {url: `/api/v1/reviews/${reviewId}/context`, method: 'GET', signal
    },
      options);
    }




export const getGetReviewContextQueryKey = (reviewId: string,) => {
    return [
    `/api/v1/reviews/${reviewId}/context`
    ] as const;
    }


export const getGetReviewContextQueryOptions = <TData = Awaited<ReturnType<typeof getReviewContext>>, TError = ErrorType<HTTPValidationError>>(reviewId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewContext>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReviewContextQueryKey(reviewId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReviewContext>>> = ({ signal }) => getReviewContext(reviewId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: reviewId !== null && reviewId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReviewContext>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReviewContextQueryResult = NonNullable<Awaited<ReturnType<typeof getReviewContext>>>
export type GetReviewContextQueryError = ErrorType<HTTPValidationError>


export function useGetReviewContext<TData = Awaited<ReturnType<typeof getReviewContext>>, TError = ErrorType<HTTPValidationError>>(
 reviewId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewContext>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewContext>>,
          TError,
          Awaited<ReturnType<typeof getReviewContext>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReviewContext<TData = Awaited<ReturnType<typeof getReviewContext>>, TError = ErrorType<HTTPValidationError>>(
 reviewId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewContext>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewContext>>,
          TError,
          Awaited<ReturnType<typeof getReviewContext>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReviewContext<TData = Awaited<ReturnType<typeof getReviewContext>>, TError = ErrorType<HTTPValidationError>>(
 reviewId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewContext>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Review Context
 */

export function useGetReviewContext<TData = Awaited<ReturnType<typeof getReviewContext>>, TError = ErrorType<HTTPValidationError>>(
 reviewId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewContext>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReviewContextQueryOptions(reviewId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Correct Review
 */
export const correctReview = (
    reviewId: string,
    correctReviewRequest: BodyType<CorrectReviewRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewMutationResponse>(
      {url: `/api/v1/reviews/${reviewId}/correct`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: correctReviewRequest, signal
    },
      options);
    }




export const getCorrectReviewMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof correctReview>>, TError,{reviewId: string;data: BodyType<CorrectReviewRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof correctReview>>, TError,{reviewId: string;data: BodyType<CorrectReviewRequest>}, TContext> => {

const mutationKey = ['correctReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof correctReview>>, {reviewId: string;data: BodyType<CorrectReviewRequest>}> = (props) => {
          const {reviewId,data} = props ?? {};

          return  correctReview(reviewId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CorrectReviewMutationResult = NonNullable<Awaited<ReturnType<typeof correctReview>>>
    export type CorrectReviewMutationBody = BodyType<CorrectReviewRequest>
    export type CorrectReviewMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Correct Review
 */
export const useCorrectReview = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof correctReview>>, TError,{reviewId: string;data: BodyType<CorrectReviewRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof correctReview>>,
        TError,
        {reviewId: string;data: BodyType<CorrectReviewRequest>},
        TContext
      > => {
      return useMutation(getCorrectReviewMutationOptions(options), queryClient);
    }
    /**
 * @summary Reject Review
 */
export const rejectReview = (
    reviewId: string,
    rejectReviewRequest: BodyType<RejectReviewRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewMutationResponse>(
      {url: `/api/v1/reviews/${reviewId}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rejectReviewRequest, signal
    },
      options);
    }




export const getRejectReviewMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectReview>>, TError,{reviewId: string;data: BodyType<RejectReviewRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof rejectReview>>, TError,{reviewId: string;data: BodyType<RejectReviewRequest>}, TContext> => {

const mutationKey = ['rejectReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectReview>>, {reviewId: string;data: BodyType<RejectReviewRequest>}> = (props) => {
          const {reviewId,data} = props ?? {};

          return  rejectReview(reviewId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RejectReviewMutationResult = NonNullable<Awaited<ReturnType<typeof rejectReview>>>
    export type RejectReviewMutationBody = BodyType<RejectReviewRequest>
    export type RejectReviewMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Reject Review
 */
export const useRejectReview = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectReview>>, TError,{reviewId: string;data: BodyType<RejectReviewRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectReview>>,
        TError,
        {reviewId: string;data: BodyType<RejectReviewRequest>},
        TContext
      > => {
      return useMutation(getRejectReviewMutationOptions(options), queryClient);
    }
