/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CorrectReviewRequest,
  HTTPValidationError,
  ListDraftReviewsApiV1ReviewsGetParams,
  ReviewItemResponse
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listDraftReviewsApiV1ReviewsGetResponse200 = {
  data: ReviewItemResponse[]
  status: 200
}

export type listDraftReviewsApiV1ReviewsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listDraftReviewsApiV1ReviewsGetResponseSuccess = (listDraftReviewsApiV1ReviewsGetResponse200) & {
  headers: Headers;
};
export type listDraftReviewsApiV1ReviewsGetResponseError = (listDraftReviewsApiV1ReviewsGetResponse422) & {
  headers: Headers;
};

export type listDraftReviewsApiV1ReviewsGetResponse = (listDraftReviewsApiV1ReviewsGetResponseSuccess | listDraftReviewsApiV1ReviewsGetResponseError)

export const getListDraftReviewsApiV1ReviewsGetUrl = (params?: ListDraftReviewsApiV1ReviewsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/reviews?${stringifiedParams}` : `/api/v1/reviews`
}

/**
 * @summary List Draft Reviews
 */
export const listDraftReviewsApiV1ReviewsGet = async (params?: ListDraftReviewsApiV1ReviewsGetParams, options?: RequestInit): Promise<listDraftReviewsApiV1ReviewsGetResponse> => {

  return customInstance<listDraftReviewsApiV1ReviewsGetResponse>(getListDraftReviewsApiV1ReviewsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDraftReviewsApiV1ReviewsGetQueryKey = (params?: ListDraftReviewsApiV1ReviewsGetParams,) => {
    return [
    `/api/v1/reviews`, ...(params ? [params] : [])
    ] as const;
    }


export const getListDraftReviewsApiV1ReviewsGetQueryOptions = <TData = Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError = HTTPValidationError>(params?: ListDraftReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDraftReviewsApiV1ReviewsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>> = ({ signal }) => listDraftReviewsApiV1ReviewsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDraftReviewsApiV1ReviewsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>>
export type ListDraftReviewsApiV1ReviewsGetQueryError = HTTPValidationError


export function useListDraftReviewsApiV1ReviewsGet<TData = Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListDraftReviewsApiV1ReviewsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>,
          TError,
          Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDraftReviewsApiV1ReviewsGet<TData = Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError = HTTPValidationError>(
 params?: ListDraftReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>,
          TError,
          Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDraftReviewsApiV1ReviewsGet<TData = Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError = HTTPValidationError>(
 params?: ListDraftReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Draft Reviews
 */

export function useListDraftReviewsApiV1ReviewsGet<TData = Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError = HTTPValidationError>(
 params?: ListDraftReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDraftReviewsApiV1ReviewsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDraftReviewsApiV1ReviewsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approveReviewApiV1ReviewsReviewIdApprovePostResponse200 = {
  data: unknown
  status: 200
}

export type approveReviewApiV1ReviewsReviewIdApprovePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type approveReviewApiV1ReviewsReviewIdApprovePostResponseSuccess = (approveReviewApiV1ReviewsReviewIdApprovePostResponse200) & {
  headers: Headers;
};
export type approveReviewApiV1ReviewsReviewIdApprovePostResponseError = (approveReviewApiV1ReviewsReviewIdApprovePostResponse422) & {
  headers: Headers;
};

export type approveReviewApiV1ReviewsReviewIdApprovePostResponse = (approveReviewApiV1ReviewsReviewIdApprovePostResponseSuccess | approveReviewApiV1ReviewsReviewIdApprovePostResponseError)

export const getApproveReviewApiV1ReviewsReviewIdApprovePostUrl = (reviewId: string,) => {




  return `/api/v1/reviews/${reviewId}/approve`
}

/**
 * @summary Approve Review
 */
export const approveReviewApiV1ReviewsReviewIdApprovePost = async (reviewId: string, options?: RequestInit): Promise<approveReviewApiV1ReviewsReviewIdApprovePostResponse> => {

  return customInstance<approveReviewApiV1ReviewsReviewIdApprovePostResponse>(getApproveReviewApiV1ReviewsReviewIdApprovePostUrl(reviewId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getApproveReviewApiV1ReviewsReviewIdApprovePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveReviewApiV1ReviewsReviewIdApprovePost>>, TError,{reviewId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof approveReviewApiV1ReviewsReviewIdApprovePost>>, TError,{reviewId: string}, TContext> => {

const mutationKey = ['approveReviewApiV1ReviewsReviewIdApprovePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveReviewApiV1ReviewsReviewIdApprovePost>>, {reviewId: string}> = (props) => {
          const {reviewId} = props ?? {};

          return  approveReviewApiV1ReviewsReviewIdApprovePost(reviewId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApproveReviewApiV1ReviewsReviewIdApprovePostMutationResult = NonNullable<Awaited<ReturnType<typeof approveReviewApiV1ReviewsReviewIdApprovePost>>>

    export type ApproveReviewApiV1ReviewsReviewIdApprovePostMutationError = HTTPValidationError

    /**
 * @summary Approve Review
 */
export const useApproveReviewApiV1ReviewsReviewIdApprovePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveReviewApiV1ReviewsReviewIdApprovePost>>, TError,{reviewId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approveReviewApiV1ReviewsReviewIdApprovePost>>,
        TError,
        {reviewId: string},
        TContext
      > => {
      return useMutation(getApproveReviewApiV1ReviewsReviewIdApprovePostMutationOptions(options), queryClient);
    }
    export type rejectReviewApiV1ReviewsReviewIdRejectPostResponse200 = {
  data: unknown
  status: 200
}

export type rejectReviewApiV1ReviewsReviewIdRejectPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type rejectReviewApiV1ReviewsReviewIdRejectPostResponseSuccess = (rejectReviewApiV1ReviewsReviewIdRejectPostResponse200) & {
  headers: Headers;
};
export type rejectReviewApiV1ReviewsReviewIdRejectPostResponseError = (rejectReviewApiV1ReviewsReviewIdRejectPostResponse422) & {
  headers: Headers;
};

export type rejectReviewApiV1ReviewsReviewIdRejectPostResponse = (rejectReviewApiV1ReviewsReviewIdRejectPostResponseSuccess | rejectReviewApiV1ReviewsReviewIdRejectPostResponseError)

export const getRejectReviewApiV1ReviewsReviewIdRejectPostUrl = (reviewId: string,) => {




  return `/api/v1/reviews/${reviewId}/reject`
}

/**
 * @summary Reject Review
 */
export const rejectReviewApiV1ReviewsReviewIdRejectPost = async (reviewId: string, options?: RequestInit): Promise<rejectReviewApiV1ReviewsReviewIdRejectPostResponse> => {

  return customInstance<rejectReviewApiV1ReviewsReviewIdRejectPostResponse>(getRejectReviewApiV1ReviewsReviewIdRejectPostUrl(reviewId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getRejectReviewApiV1ReviewsReviewIdRejectPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectReviewApiV1ReviewsReviewIdRejectPost>>, TError,{reviewId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof rejectReviewApiV1ReviewsReviewIdRejectPost>>, TError,{reviewId: string}, TContext> => {

const mutationKey = ['rejectReviewApiV1ReviewsReviewIdRejectPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectReviewApiV1ReviewsReviewIdRejectPost>>, {reviewId: string}> = (props) => {
          const {reviewId} = props ?? {};

          return  rejectReviewApiV1ReviewsReviewIdRejectPost(reviewId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RejectReviewApiV1ReviewsReviewIdRejectPostMutationResult = NonNullable<Awaited<ReturnType<typeof rejectReviewApiV1ReviewsReviewIdRejectPost>>>

    export type RejectReviewApiV1ReviewsReviewIdRejectPostMutationError = HTTPValidationError

    /**
 * @summary Reject Review
 */
export const useRejectReviewApiV1ReviewsReviewIdRejectPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectReviewApiV1ReviewsReviewIdRejectPost>>, TError,{reviewId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectReviewApiV1ReviewsReviewIdRejectPost>>,
        TError,
        {reviewId: string},
        TContext
      > => {
      return useMutation(getRejectReviewApiV1ReviewsReviewIdRejectPostMutationOptions(options), queryClient);
    }
    export type correctReviewApiV1ReviewsReviewIdCorrectPostResponse200 = {
  data: unknown
  status: 200
}

export type correctReviewApiV1ReviewsReviewIdCorrectPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type correctReviewApiV1ReviewsReviewIdCorrectPostResponseSuccess = (correctReviewApiV1ReviewsReviewIdCorrectPostResponse200) & {
  headers: Headers;
};
export type correctReviewApiV1ReviewsReviewIdCorrectPostResponseError = (correctReviewApiV1ReviewsReviewIdCorrectPostResponse422) & {
  headers: Headers;
};

export type correctReviewApiV1ReviewsReviewIdCorrectPostResponse = (correctReviewApiV1ReviewsReviewIdCorrectPostResponseSuccess | correctReviewApiV1ReviewsReviewIdCorrectPostResponseError)

export const getCorrectReviewApiV1ReviewsReviewIdCorrectPostUrl = (reviewId: string,) => {




  return `/api/v1/reviews/${reviewId}/correct`
}

/**
 * @summary Correct Review
 */
export const correctReviewApiV1ReviewsReviewIdCorrectPost = async (reviewId: string,
    correctReviewRequest: CorrectReviewRequest, options?: RequestInit): Promise<correctReviewApiV1ReviewsReviewIdCorrectPostResponse> => {

  return customInstance<correctReviewApiV1ReviewsReviewIdCorrectPostResponse>(getCorrectReviewApiV1ReviewsReviewIdCorrectPostUrl(reviewId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(correctReviewRequest)
  }
);}





export const getCorrectReviewApiV1ReviewsReviewIdCorrectPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof correctReviewApiV1ReviewsReviewIdCorrectPost>>, TError,{reviewId: string;data: CorrectReviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof correctReviewApiV1ReviewsReviewIdCorrectPost>>, TError,{reviewId: string;data: CorrectReviewRequest}, TContext> => {

const mutationKey = ['correctReviewApiV1ReviewsReviewIdCorrectPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof correctReviewApiV1ReviewsReviewIdCorrectPost>>, {reviewId: string;data: CorrectReviewRequest}> = (props) => {
          const {reviewId,data} = props ?? {};

          return  correctReviewApiV1ReviewsReviewIdCorrectPost(reviewId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CorrectReviewApiV1ReviewsReviewIdCorrectPostMutationResult = NonNullable<Awaited<ReturnType<typeof correctReviewApiV1ReviewsReviewIdCorrectPost>>>
    export type CorrectReviewApiV1ReviewsReviewIdCorrectPostMutationBody = CorrectReviewRequest
    export type CorrectReviewApiV1ReviewsReviewIdCorrectPostMutationError = HTTPValidationError

    /**
 * @summary Correct Review
 */
export const useCorrectReviewApiV1ReviewsReviewIdCorrectPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof correctReviewApiV1ReviewsReviewIdCorrectPost>>, TError,{reviewId: string;data: CorrectReviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof correctReviewApiV1ReviewsReviewIdCorrectPost>>,
        TError,
        {reviewId: string;data: CorrectReviewRequest},
        TContext
      > => {
      return useMutation(getCorrectReviewApiV1ReviewsReviewIdCorrectPostMutationOptions(options), queryClient);
    }
