/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  SetActiveFirmApiV1SessionActiveFirmPostParams
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type setActiveFirmApiV1SessionActiveFirmPostResponse200 = {
  data: unknown
  status: 200
}

export type setActiveFirmApiV1SessionActiveFirmPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type setActiveFirmApiV1SessionActiveFirmPostResponseSuccess = (setActiveFirmApiV1SessionActiveFirmPostResponse200) & {
  headers: Headers;
};
export type setActiveFirmApiV1SessionActiveFirmPostResponseError = (setActiveFirmApiV1SessionActiveFirmPostResponse422) & {
  headers: Headers;
};

export type setActiveFirmApiV1SessionActiveFirmPostResponse = (setActiveFirmApiV1SessionActiveFirmPostResponseSuccess | setActiveFirmApiV1SessionActiveFirmPostResponseError)

export const getSetActiveFirmApiV1SessionActiveFirmPostUrl = (params: SetActiveFirmApiV1SessionActiveFirmPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/session/active-firm?${stringifiedParams}` : `/api/v1/session/active-firm`
}

/**
 * Verified tenant switch flow.
 * Validates that the currently authenticated user is an active member of the requested firm.
 * Returns the firm details and role, which the frontend can then use to set the x-tenant-id header.
 * @summary Set Active Firm
 */
export const setActiveFirmApiV1SessionActiveFirmPost = async (params: SetActiveFirmApiV1SessionActiveFirmPostParams, options?: RequestInit): Promise<setActiveFirmApiV1SessionActiveFirmPostResponse> => {

  return customInstance<setActiveFirmApiV1SessionActiveFirmPostResponse>(getSetActiveFirmApiV1SessionActiveFirmPostUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}





export const getSetActiveFirmApiV1SessionActiveFirmPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setActiveFirmApiV1SessionActiveFirmPost>>, TError,{params: SetActiveFirmApiV1SessionActiveFirmPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof setActiveFirmApiV1SessionActiveFirmPost>>, TError,{params: SetActiveFirmApiV1SessionActiveFirmPostParams}, TContext> => {

const mutationKey = ['setActiveFirmApiV1SessionActiveFirmPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setActiveFirmApiV1SessionActiveFirmPost>>, {params: SetActiveFirmApiV1SessionActiveFirmPostParams}> = (props) => {
          const {params} = props ?? {};

          return  setActiveFirmApiV1SessionActiveFirmPost(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetActiveFirmApiV1SessionActiveFirmPostMutationResult = NonNullable<Awaited<ReturnType<typeof setActiveFirmApiV1SessionActiveFirmPost>>>

    export type SetActiveFirmApiV1SessionActiveFirmPostMutationError = HTTPValidationError

    /**
 * @summary Set Active Firm
 */
export const useSetActiveFirmApiV1SessionActiveFirmPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setActiveFirmApiV1SessionActiveFirmPost>>, TError,{params: SetActiveFirmApiV1SessionActiveFirmPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setActiveFirmApiV1SessionActiveFirmPost>>,
        TError,
        {params: SetActiveFirmApiV1SessionActiveFirmPostParams},
        TContext
      > => {
      return useMutation(getSetActiveFirmApiV1SessionActiveFirmPostMutationOptions(options), queryClient);
    }
