/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSystemDependencies200,
  HTTPValidationError,
  HealthResponse,
  SyncMesaCoreParams,
  SystemSettingsResponse
} from '../../models';

import { customInstance } from '../../../lib/api/client';
import type { ErrorType , BodyType } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary System Dependencies
 */
export const getSystemDependencies = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetSystemDependencies200>(
      {url: `/api/v1/system/dependencies`, method: 'GET', signal
    },
      options);
    }




export const getGetSystemDependenciesQueryKey = () => {
    return [
    `/api/v1/system/dependencies`
    ] as const;
    }


export const getGetSystemDependenciesQueryOptions = <TData = Awaited<ReturnType<typeof getSystemDependencies>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDependencies>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSystemDependenciesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSystemDependencies>>> = ({ signal }) => getSystemDependencies(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSystemDependencies>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSystemDependenciesQueryResult = NonNullable<Awaited<ReturnType<typeof getSystemDependencies>>>
export type GetSystemDependenciesQueryError = ErrorType<unknown>


export function useGetSystemDependencies<TData = Awaited<ReturnType<typeof getSystemDependencies>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDependencies>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemDependencies>>,
          TError,
          Awaited<ReturnType<typeof getSystemDependencies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemDependencies<TData = Awaited<ReturnType<typeof getSystemDependencies>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDependencies>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemDependencies>>,
          TError,
          Awaited<ReturnType<typeof getSystemDependencies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemDependencies<TData = Awaited<ReturnType<typeof getSystemDependencies>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDependencies>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary System Dependencies
 */

export function useGetSystemDependencies<TData = Awaited<ReturnType<typeof getSystemDependencies>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDependencies>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSystemDependenciesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Get System Settings
 */
export const getSystemSettings = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SystemSettingsResponse>(
      {url: `/api/v1/system/settings`, method: 'GET', signal
    },
      options);
    }




export const getGetSystemSettingsQueryKey = () => {
    return [
    `/api/v1/system/settings`
    ] as const;
    }


export const getGetSystemSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSystemSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSystemSettings>>> = ({ signal }) => getSystemSettings(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSystemSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSystemSettings>>>
export type GetSystemSettingsQueryError = ErrorType<unknown>


export function useGetSystemSettings<TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemSettings>>,
          TError,
          Awaited<ReturnType<typeof getSystemSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemSettings<TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemSettings>>,
          TError,
          Awaited<ReturnType<typeof getSystemSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemSettings<TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get System Settings
 */

export function useGetSystemSettings<TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSystemSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Update System Settings
 */
export const updateSystemSettings = (
    systemSettingsResponse: BodyType<SystemSettingsResponse>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/system/settings`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: systemSettingsResponse, signal
    },
      options);
    }




export const getUpdateSystemSettingsMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSystemSettings>>, TError,{data: BodyType<SystemSettingsResponse>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSystemSettings>>, TError,{data: BodyType<SystemSettingsResponse>}, TContext> => {

const mutationKey = ['updateSystemSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSystemSettings>>, {data: BodyType<SystemSettingsResponse>}> = (props) => {
          const {data} = props ?? {};

          return  updateSystemSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSystemSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updateSystemSettings>>>
    export type UpdateSystemSettingsMutationBody = BodyType<SystemSettingsResponse>
    export type UpdateSystemSettingsMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update System Settings
 */
export const useUpdateSystemSettings = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSystemSettings>>, TError,{data: BodyType<SystemSettingsResponse>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSystemSettings>>,
        TError,
        {data: BodyType<SystemSettingsResponse>},
        TContext
      > => {
      return useMutation(getUpdateSystemSettingsMutationOptions(options), queryClient);
    }
    /**
 * @summary Sync Mesa Core
 */
export const syncMesaCore = (
    params?: SyncMesaCoreParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/system/sync-mesa-core`, method: 'POST',
        params, signal
    },
      options);
    }




export const getSyncMesaCoreMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncMesaCore>>, TError,{params?: SyncMesaCoreParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof syncMesaCore>>, TError,{params?: SyncMesaCoreParams}, TContext> => {

const mutationKey = ['syncMesaCore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncMesaCore>>, {params?: SyncMesaCoreParams}> = (props) => {
          const {params} = props ?? {};

          return  syncMesaCore(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncMesaCoreMutationResult = NonNullable<Awaited<ReturnType<typeof syncMesaCore>>>

    export type SyncMesaCoreMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Sync Mesa Core
 */
export const useSyncMesaCore = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncMesaCore>>, TError,{params?: SyncMesaCoreParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncMesaCore>>,
        TError,
        {params?: SyncMesaCoreParams},
        TContext
      > => {
      return useMutation(getSyncMesaCoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Live
 */
export const liveProbe = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<HealthResponse>(
      {url: `/health/live`, method: 'GET', signal
    },
      options);
    }




export const getLiveProbeQueryKey = () => {
    return [
    `/health/live`
    ] as const;
    }


export const getLiveProbeQueryOptions = <TData = Awaited<ReturnType<typeof liveProbe>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveProbe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLiveProbeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof liveProbe>>> = ({ signal }) => liveProbe(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof liveProbe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LiveProbeQueryResult = NonNullable<Awaited<ReturnType<typeof liveProbe>>>
export type LiveProbeQueryError = ErrorType<unknown>


export function useLiveProbe<TData = Awaited<ReturnType<typeof liveProbe>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveProbe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof liveProbe>>,
          TError,
          Awaited<ReturnType<typeof liveProbe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLiveProbe<TData = Awaited<ReturnType<typeof liveProbe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveProbe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof liveProbe>>,
          TError,
          Awaited<ReturnType<typeof liveProbe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLiveProbe<TData = Awaited<ReturnType<typeof liveProbe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveProbe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Live
 */

export function useLiveProbe<TData = Awaited<ReturnType<typeof liveProbe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveProbe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLiveProbeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Ready
 */
export const readyProbe = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<HealthResponse>(
      {url: `/health/ready`, method: 'GET', signal
    },
      options);
    }




export const getReadyProbeQueryKey = () => {
    return [
    `/health/ready`
    ] as const;
    }


export const getReadyProbeQueryOptions = <TData = Awaited<ReturnType<typeof readyProbe>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyProbe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadyProbeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readyProbe>>> = ({ signal }) => readyProbe(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readyProbe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadyProbeQueryResult = NonNullable<Awaited<ReturnType<typeof readyProbe>>>
export type ReadyProbeQueryError = ErrorType<unknown>


export function useReadyProbe<TData = Awaited<ReturnType<typeof readyProbe>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyProbe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readyProbe>>,
          TError,
          Awaited<ReturnType<typeof readyProbe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadyProbe<TData = Awaited<ReturnType<typeof readyProbe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyProbe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readyProbe>>,
          TError,
          Awaited<ReturnType<typeof readyProbe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadyProbe<TData = Awaited<ReturnType<typeof readyProbe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyProbe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ready
 */

export function useReadyProbe<TData = Awaited<ReturnType<typeof readyProbe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyProbe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadyProbeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






