/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  SyncMesaCoreRequest,
  UpdateSystemSettingsBody
} from '../../models';

import { customInstance } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type liveHealthLiveGetResponse200 = {
  data: unknown
  status: 200
}

export type liveHealthLiveGetResponseSuccess = (liveHealthLiveGetResponse200) & {
  headers: Headers;
};
;

export type liveHealthLiveGetResponse = (liveHealthLiveGetResponseSuccess)

export const getLiveHealthLiveGetUrl = () => {




  return `/health/live`
}

/**
 * @summary Live
 */
export const liveHealthLiveGet = async ( options?: RequestInit): Promise<liveHealthLiveGetResponse> => {

  return customInstance<liveHealthLiveGetResponse>(getLiveHealthLiveGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getLiveHealthLiveGetQueryKey = () => {
    return [
    `/health/live`
    ] as const;
    }


export const getLiveHealthLiveGetQueryOptions = <TData = Awaited<ReturnType<typeof liveHealthLiveGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveHealthLiveGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLiveHealthLiveGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof liveHealthLiveGet>>> = ({ signal }) => liveHealthLiveGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof liveHealthLiveGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LiveHealthLiveGetQueryResult = NonNullable<Awaited<ReturnType<typeof liveHealthLiveGet>>>
export type LiveHealthLiveGetQueryError = unknown


export function useLiveHealthLiveGet<TData = Awaited<ReturnType<typeof liveHealthLiveGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveHealthLiveGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof liveHealthLiveGet>>,
          TError,
          Awaited<ReturnType<typeof liveHealthLiveGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLiveHealthLiveGet<TData = Awaited<ReturnType<typeof liveHealthLiveGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveHealthLiveGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof liveHealthLiveGet>>,
          TError,
          Awaited<ReturnType<typeof liveHealthLiveGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLiveHealthLiveGet<TData = Awaited<ReturnType<typeof liveHealthLiveGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveHealthLiveGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Live
 */

export function useLiveHealthLiveGet<TData = Awaited<ReturnType<typeof liveHealthLiveGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveHealthLiveGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLiveHealthLiveGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type readyHealthReadyGetResponse200 = {
  data: unknown
  status: 200
}

export type readyHealthReadyGetResponseSuccess = (readyHealthReadyGetResponse200) & {
  headers: Headers;
};
;

export type readyHealthReadyGetResponse = (readyHealthReadyGetResponseSuccess)

export const getReadyHealthReadyGetUrl = () => {




  return `/health/ready`
}

/**
 * @summary Ready
 */
export const readyHealthReadyGet = async ( options?: RequestInit): Promise<readyHealthReadyGetResponse> => {

  return customInstance<readyHealthReadyGetResponse>(getReadyHealthReadyGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReadyHealthReadyGetQueryKey = () => {
    return [
    `/health/ready`
    ] as const;
    }


export const getReadyHealthReadyGetQueryOptions = <TData = Awaited<ReturnType<typeof readyHealthReadyGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyHealthReadyGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadyHealthReadyGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readyHealthReadyGet>>> = ({ signal }) => readyHealthReadyGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readyHealthReadyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadyHealthReadyGetQueryResult = NonNullable<Awaited<ReturnType<typeof readyHealthReadyGet>>>
export type ReadyHealthReadyGetQueryError = unknown


export function useReadyHealthReadyGet<TData = Awaited<ReturnType<typeof readyHealthReadyGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyHealthReadyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readyHealthReadyGet>>,
          TError,
          Awaited<ReturnType<typeof readyHealthReadyGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadyHealthReadyGet<TData = Awaited<ReturnType<typeof readyHealthReadyGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyHealthReadyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readyHealthReadyGet>>,
          TError,
          Awaited<ReturnType<typeof readyHealthReadyGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadyHealthReadyGet<TData = Awaited<ReturnType<typeof readyHealthReadyGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyHealthReadyGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ready
 */

export function useReadyHealthReadyGet<TData = Awaited<ReturnType<typeof readyHealthReadyGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyHealthReadyGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadyHealthReadyGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type systemDependenciesApiV1SystemDependenciesGetResponse200 = {
  data: unknown
  status: 200
}

export type systemDependenciesApiV1SystemDependenciesGetResponseSuccess = (systemDependenciesApiV1SystemDependenciesGetResponse200) & {
  headers: Headers;
};
;

export type systemDependenciesApiV1SystemDependenciesGetResponse = (systemDependenciesApiV1SystemDependenciesGetResponseSuccess)

export const getSystemDependenciesApiV1SystemDependenciesGetUrl = () => {




  return `/api/v1/system/dependencies`
}

/**
 * @summary System Dependencies
 */
export const systemDependenciesApiV1SystemDependenciesGet = async ( options?: RequestInit): Promise<systemDependenciesApiV1SystemDependenciesGetResponse> => {

  return customInstance<systemDependenciesApiV1SystemDependenciesGetResponse>(getSystemDependenciesApiV1SystemDependenciesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSystemDependenciesApiV1SystemDependenciesGetQueryKey = () => {
    return [
    `/api/v1/system/dependencies`
    ] as const;
    }


export const getSystemDependenciesApiV1SystemDependenciesGetQueryOptions = <TData = Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemDependenciesApiV1SystemDependenciesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>> = ({ signal }) => systemDependenciesApiV1SystemDependenciesGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SystemDependenciesApiV1SystemDependenciesGetQueryResult = NonNullable<Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>>
export type SystemDependenciesApiV1SystemDependenciesGetQueryError = unknown


export function useSystemDependenciesApiV1SystemDependenciesGet<TData = Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>,
          TError,
          Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSystemDependenciesApiV1SystemDependenciesGet<TData = Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>,
          TError,
          Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSystemDependenciesApiV1SystemDependenciesGet<TData = Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary System Dependencies
 */

export function useSystemDependenciesApiV1SystemDependenciesGet<TData = Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemDependenciesApiV1SystemDependenciesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSystemDependenciesApiV1SystemDependenciesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getSystemSettingsResponse200 = {
  data: unknown
  status: 200
}

export type getSystemSettingsResponseSuccess = (getSystemSettingsResponse200) & {
  headers: Headers;
};
;

export type getSystemSettingsResponse = (getSystemSettingsResponseSuccess)

export const getGetSystemSettingsUrl = () => {




  return `/api/v1/system/settings`
}

/**
 * @summary Get System Settings
 */
export const getSystemSettings = async ( options?: RequestInit): Promise<getSystemSettingsResponse> => {

  return customInstance<getSystemSettingsResponse>(getGetSystemSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSystemSettingsQueryKey = () => {
    return [
    `/api/v1/system/settings`
    ] as const;
    }


export const getGetSystemSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSystemSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSystemSettings>>> = ({ signal }) => getSystemSettings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSystemSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSystemSettings>>>
export type GetSystemSettingsQueryError = unknown


export function useGetSystemSettings<TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemSettings>>,
          TError,
          Awaited<ReturnType<typeof getSystemSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemSettings<TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemSettings>>,
          TError,
          Awaited<ReturnType<typeof getSystemSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemSettings<TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get System Settings
 */

export function useGetSystemSettings<TData = Awaited<ReturnType<typeof getSystemSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSystemSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateSystemSettingsResponse200 = {
  data: unknown
  status: 200
}

export type updateSystemSettingsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateSystemSettingsResponseSuccess = (updateSystemSettingsResponse200) & {
  headers: Headers;
};
export type updateSystemSettingsResponseError = (updateSystemSettingsResponse422) & {
  headers: Headers;
};

export type updateSystemSettingsResponse = (updateSystemSettingsResponseSuccess | updateSystemSettingsResponseError)

export const getUpdateSystemSettingsUrl = () => {




  return `/api/v1/system/settings`
}

/**
 * @summary Update System Settings
 */
export const updateSystemSettings = async (updateSystemSettingsBody: UpdateSystemSettingsBody, options?: RequestInit): Promise<updateSystemSettingsResponse> => {

  return customInstance<updateSystemSettingsResponse>(getUpdateSystemSettingsUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSystemSettingsBody)
  }
);}





export const getUpdateSystemSettingsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSystemSettings>>, TError,{data: UpdateSystemSettingsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSystemSettings>>, TError,{data: UpdateSystemSettingsBody}, TContext> => {

const mutationKey = ['updateSystemSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSystemSettings>>, {data: UpdateSystemSettingsBody}> = (props) => {
          const {data} = props ?? {};

          return  updateSystemSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSystemSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updateSystemSettings>>>
    export type UpdateSystemSettingsMutationBody = UpdateSystemSettingsBody
    export type UpdateSystemSettingsMutationError = HTTPValidationError

    /**
 * @summary Update System Settings
 */
export const useUpdateSystemSettings = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSystemSettings>>, TError,{data: UpdateSystemSettingsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSystemSettings>>,
        TError,
        {data: UpdateSystemSettingsBody},
        TContext
      > => {
      return useMutation(getUpdateSystemSettingsMutationOptions(options), queryClient);
    }
    export type syncMesaCoreResponse200 = {
  data: unknown
  status: 200
}

export type syncMesaCoreResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type syncMesaCoreResponseSuccess = (syncMesaCoreResponse200) & {
  headers: Headers;
};
export type syncMesaCoreResponseError = (syncMesaCoreResponse422) & {
  headers: Headers;
};

export type syncMesaCoreResponse = (syncMesaCoreResponseSuccess | syncMesaCoreResponseError)

export const getSyncMesaCoreUrl = () => {




  return `/api/v1/system/sync-mesa-core`
}

/**
 * @summary Sync Mesa Core
 */
export const syncMesaCore = async (syncMesaCoreRequest: SyncMesaCoreRequest, options?: RequestInit): Promise<syncMesaCoreResponse> => {

  return customInstance<syncMesaCoreResponse>(getSyncMesaCoreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(syncMesaCoreRequest)
  }
);}





export const getSyncMesaCoreMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncMesaCore>>, TError,{data: SyncMesaCoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof syncMesaCore>>, TError,{data: SyncMesaCoreRequest}, TContext> => {

const mutationKey = ['syncMesaCore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncMesaCore>>, {data: SyncMesaCoreRequest}> = (props) => {
          const {data} = props ?? {};

          return  syncMesaCore(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncMesaCoreMutationResult = NonNullable<Awaited<ReturnType<typeof syncMesaCore>>>
    export type SyncMesaCoreMutationBody = SyncMesaCoreRequest
    export type SyncMesaCoreMutationError = HTTPValidationError

    /**
 * @summary Sync Mesa Core
 */
export const useSyncMesaCore = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncMesaCore>>, TError,{data: SyncMesaCoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncMesaCore>>,
        TError,
        {data: SyncMesaCoreRequest},
        TContext
      > => {
      return useMutation(getSyncMesaCoreMutationOptions(options), queryClient);
    }
