/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { AuditEventResponseChanges } from './auditEventResponseChanges';

export interface AuditEventResponse {
  id: string;
  user_id?: string | null;
  action: string;
  entity_type: string;
  entity_id: string;
  changes?: AuditEventResponseChanges;
  timestamp: string;
}
