/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface ClaimResponse {
  claimant_party_id: string;
  defendant_party_id: string;
  description: string;
  id: string;
  matter_id: string;
  review_status: string;
  source_locator_id: string | null;
  status: string;
}
