/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface ConflictResult {
  matched_name: string;
  matter_id: string;
  matter_title: string;
  role: string;
  searched_name: string;
  status: string;
}
