/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { CorrectReviewRequestCorrectedContent } from './correctReviewRequestCorrectedContent';

export interface CorrectReviewRequest {
  corrected_content: CorrectReviewRequestCorrectedContent;
  /** @minimum 1 */
  expected_version: number;
  /**
     * @minLength 3
     * @maxLength 1000
     */
  reason: string;
}
