/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardMetricsResponse {
  active_matters: number;
  degraded_capabilities: string[];
  failed_operations: number;
  pending_reviews: number;
  system_status: string;
  unread_notifications: number;
  upcoming_deadlines: number;
}
