/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface DeadlineResponse {
  description: string;
  due_date: string;
  id: string;
  is_completed: boolean;
  matter_id: string;
}
