/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface DocumentRevisionViewerResponse {
  id: string;
  immutable_at?: string | null;
  mime_type: string;
  provenance_state: string;
  scan_status: string;
  sha256?: string | null;
  size_bytes?: number | null;
  version: number;
}
