/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface DocumentResponse {
  created_at: string;
  failure_reason?: string | null;
  id: string;
  latest_revision_id?: string | null;
  matter_id: string;
  provenance_state: string;
  status: string;
  title: string;
}
