/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface DownloadResponse {
  expires_in_seconds: number;
  presigned_url: string;
}
