/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface DraftCitationResponse {
  citation_text: string;
  document_id: string | null;
  id: string;
  verification_state: string;
}
