/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface DraftDetailResponse {
  content: string;
  etag?: string | null;
  id: string;
  matter_id: string;
  status: string;
  title: string;
  updated_at: string | null;
  version: number;
}
