/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface FirmCreateRequest {
  /**
     * @minLength 2
     * @maxLength 100
     */
  name: string;
}
