/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { HealthResponseComponents } from './healthResponseComponents';

export interface HealthResponse {
  components: HealthResponseComponents;
  status: string;
}
