/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { JobResponsePayload } from './jobResponsePayload';

export interface JobResponse {
  created_at: string;
  error_message?: string | null;
  id: string;
  matter_id?: string | null;
  max_retries: number;
  payload: JobResponsePayload;
  retries: number;
  status: string;
  tenant_id: string;
  type: string;
  updated_at: string;
}
