/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface LegalSourceResponse {
  citation: string;
  content: string;
  id: string;
  source_type: string;
  title: string;
}
