/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export type ListDraftReviewsApiV1ReviewsGetParams = {
matter_id?: string | null;
status?: string | null;
entity_type?: string | null;
};
