/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface MatterCreate {
  /**
     * The title of the matter
     * @minLength 3
     * @maxLength 255
     */
  title: string;
  /** Internal reference ID */
  internal_reference?: string | null;
  /** Client name */
  client_name?: string | null;
  /** The jurisdiction of the matter */
  jurisdiction?: string | null;
  /** Type of case */
  case_type?: string | null;
  /** Confidentiality level */
  confidentiality_level?: string;
  /** AI processing policy */
  ai_processing_policy?: string;
}
