/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface MesaBindingResponse {
  agent_id: string;
  dataset_id: string;
  id: string;
  last_error: string | null;
  last_verified_at: string | null;
  matter_id: string;
  mesa_tenant_id: string;
  provisioning_status: string;
  version_id: number;
  workspace_id: string;
}
