/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { OperationalMetricsResponseMesaMutationTerminalStatuses } from './operationalMetricsResponseMesaMutationTerminalStatuses';

export interface OperationalMetricsResponse {
  document_pipeline_failures: number;
  job_queue_depth: number;
  mesa_mutation_terminal_statuses: OperationalMetricsResponseMesaMutationTerminalStatuses;
  review_backlog: number;
  stale_job_leases: number;
}
