/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface ParsedDocumentViewerResponse {
  id: string;
  ocr_version?: string | null;
  parser: string;
  parsing_revision: number;
  pipeline_version?: string | null;
  provenance_state: string;
  revision_id: string;
  status: string;
}
