/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface QAQuery {
  document_id?: string | null;
  matter_id: string;
  /**
     * @minLength 1
     * @maxLength 4096
     */
  question: string;
}
