/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { QACitation } from './qACitation';
import type { QARetrievalMetadata } from './qARetrievalMetadata';

export interface QAResponse {
  answer: string;
  citations?: QACitation[];
  degraded_reason?: string | null;
  retrieval?: QARetrievalMetadata;
  status: string;
}
