/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { QARetrievalMetadataEngine } from './qARetrievalMetadataEngine';
import type { QARetrievalMetadataScope } from './qARetrievalMetadataScope';

export interface QARetrievalMetadata {
  dataset_id?: string | null;
  duration_ms?: number;
  engine: QARetrievalMetadataEngine;
  scope: QARetrievalMetadataScope;
  verified_citation_count?: number;
  verified_document_count?: number;
}
