/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewSourceContextBbox } from './reviewSourceContextBbox';

export interface ReviewSourceContext {
  bbox?: ReviewSourceContextBbox;
  chunk_id?: string | null;
  document_id: string;
  document_title: string;
  evidence_sha256?: string | null;
  evidence_text?: string | null;
  extraction_version?: string | null;
  page_number?: number | null;
  parser_version?: string | null;
  provenance_state: string;
  revision_id: string;
  text_end?: number | null;
  text_start?: number | null;
}
