/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewItemResponseProposedContent } from './reviewItemResponseProposedContent';

export interface ReviewItemResponse {
  id: string;
  matter_id: string;
  entity_type: string;
  entity_id: string;
  proposed_content: ReviewItemResponseProposedContent;
  status: string;
}
