/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface ReviewSuggestionContext {
  confidence_category: string;
  extractor_name: string;
  extractor_version: string;
  id: string;
  parser_version: string;
  suggestion_type: string;
}
