/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface ReviewMutationRequest {
  /** @minimum 1 */
  expected_version: number;
  reason?: string | null;
}
