/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewState } from './reviewState';

export interface ReviewMutationResponse {
  id: string;
  publication_job_id?: string | null;
  status: ReviewState;
  version_id: number;
}
