/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewAuditEntryDetails } from './reviewAuditEntryDetails';

export interface ReviewAuditEntry {
  action: string;
  created_at: string;
  details: ReviewAuditEntryDetails;
  id: string;
  user_id: string;
}
