/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role';

export interface RoleElevationRequest {
  role: Role;
}
