/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface SecuritySettings {
  require_mfa: boolean;
  session_timeout_minutes: number;
}
