/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface SessionContextResponse {
  principal_id: string;
  roles: string[];
  status: string;
  tenant_id: string;
}
