/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface SupportAccessResponse {
  is_support_access_granted: boolean;
  status: string;
  support_access_granted_until: string;
}
