/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import type { FeatureSettings } from './featureSettings';
import type { RetentionSettings } from './retentionSettings';
import type { SecuritySettings } from './securitySettings';

export interface SystemSettingsResponse {
  features: FeatureSettings;
  retention: RetentionSettings;
  security: SecuritySettings;
}
