/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateDraftRequest {
  title?: string | null;
  content?: string | null;
  expected_version?: number | null;
}
