/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface UploadIntentRequest {
  /** @maxLength 255 */
  filename: string;
  matter_id: string;
  /** @maxLength 100 */
  mime_type: string;
  /**
     * File size in bytes
     * @maximum 104857600
     * @exclusiveMinimum 0
     */
  size_bytes: number;
}
