/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */

export interface UserProfileResponse {
  email: string;
  full_name: string;
  id: string;
  is_support_access_granted: boolean;
  roles: string[];
  support_access_granted_until: string | null;
}
