/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeadlineResponse,
  HTTPValidationError,
  ListDeadlinesParams
} from '../../models';

import { customInstance } from '../../../lib/api/client';
import type { ErrorType } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List Deadlines
 */
export const listDeadlines = (
    params?: ListDeadlinesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DeadlineResponse[]>(
      {url: `/api/v1/deadlines`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListDeadlinesQueryKey = (params?: ListDeadlinesParams,) => {
    return [
    `/api/v1/deadlines`, ...(params ? [params] : [])
    ] as const;
    }


export const getListDeadlinesQueryOptions = <TData = Awaited<ReturnType<typeof listDeadlines>>, TError = ErrorType<HTTPValidationError>>(params?: ListDeadlinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDeadlinesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDeadlines>>> = ({ signal }) => listDeadlines(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDeadlinesQueryResult = NonNullable<Awaited<ReturnType<typeof listDeadlines>>>
export type ListDeadlinesQueryError = ErrorType<HTTPValidationError>


export function useListDeadlines<TData = Awaited<ReturnType<typeof listDeadlines>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListDeadlinesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeadlines>>,
          TError,
          Awaited<ReturnType<typeof listDeadlines>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDeadlines<TData = Awaited<ReturnType<typeof listDeadlines>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListDeadlinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeadlines>>,
          TError,
          Awaited<ReturnType<typeof listDeadlines>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDeadlines<TData = Awaited<ReturnType<typeof listDeadlines>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListDeadlinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Deadlines
 */

export function useListDeadlines<TData = Awaited<ReturnType<typeof listDeadlines>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListDeadlinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDeadlinesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Complete Deadline
 */
export const completeDeadline = (
    deadlineId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/deadlines/${deadlineId}/complete`, method: 'POST', signal
    },
      options);
    }




export const getCompleteDeadlineMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeDeadline>>, TError,{deadlineId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof completeDeadline>>, TError,{deadlineId: string}, TContext> => {

const mutationKey = ['completeDeadline'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeDeadline>>, {deadlineId: string}> = (props) => {
          const {deadlineId} = props ?? {};

          return  completeDeadline(deadlineId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteDeadlineMutationResult = NonNullable<Awaited<ReturnType<typeof completeDeadline>>>

    export type CompleteDeadlineMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Complete Deadline
 */
export const useCompleteDeadline = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeDeadline>>, TError,{deadlineId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeDeadline>>,
        TError,
        {deadlineId: string},
        TContext
      > => {
      return useMutation(getCompleteDeadlineMutationOptions(options), queryClient);
    }
