/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeadlineResponse,
  HTTPValidationError,
  ListDeadlinesParams
} from '../../models';

import { customInstance } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listDeadlinesResponse200 = {
  data: DeadlineResponse[]
  status: 200
}

export type listDeadlinesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listDeadlinesResponseSuccess = (listDeadlinesResponse200) & {
  headers: Headers;
};
export type listDeadlinesResponseError = (listDeadlinesResponse422) & {
  headers: Headers;
};

export type listDeadlinesResponse = (listDeadlinesResponseSuccess | listDeadlinesResponseError)

export const getListDeadlinesUrl = (params?: ListDeadlinesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/deadlines?${stringifiedParams}` : `/api/v1/deadlines`
}

/**
 * @summary List Deadlines
 */
export const listDeadlines = async (params?: ListDeadlinesParams, options?: RequestInit): Promise<listDeadlinesResponse> => {

  return customInstance<listDeadlinesResponse>(getListDeadlinesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDeadlinesQueryKey = (params?: ListDeadlinesParams,) => {
    return [
    `/api/v1/deadlines`, ...(params ? [params] : [])
    ] as const;
    }


export const getListDeadlinesQueryOptions = <TData = Awaited<ReturnType<typeof listDeadlines>>, TError = HTTPValidationError>(params?: ListDeadlinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDeadlinesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDeadlines>>> = ({ signal }) => listDeadlines(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDeadlinesQueryResult = NonNullable<Awaited<ReturnType<typeof listDeadlines>>>
export type ListDeadlinesQueryError = HTTPValidationError


export function useListDeadlines<TData = Awaited<ReturnType<typeof listDeadlines>>, TError = HTTPValidationError>(
 params: undefined |  ListDeadlinesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeadlines>>,
          TError,
          Awaited<ReturnType<typeof listDeadlines>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDeadlines<TData = Awaited<ReturnType<typeof listDeadlines>>, TError = HTTPValidationError>(
 params?: ListDeadlinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeadlines>>,
          TError,
          Awaited<ReturnType<typeof listDeadlines>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDeadlines<TData = Awaited<ReturnType<typeof listDeadlines>>, TError = HTTPValidationError>(
 params?: ListDeadlinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Deadlines
 */

export function useListDeadlines<TData = Awaited<ReturnType<typeof listDeadlines>>, TError = HTTPValidationError>(
 params?: ListDeadlinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadlines>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDeadlinesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type completeDeadlineResponse200 = {
  data: unknown
  status: 200
}

export type completeDeadlineResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type completeDeadlineResponseSuccess = (completeDeadlineResponse200) & {
  headers: Headers;
};
export type completeDeadlineResponseError = (completeDeadlineResponse422) & {
  headers: Headers;
};

export type completeDeadlineResponse = (completeDeadlineResponseSuccess | completeDeadlineResponseError)

export const getCompleteDeadlineUrl = (deadlineId: string,) => {




  return `/api/v1/deadlines/${deadlineId}/complete`
}

/**
 * @summary Complete Deadline
 */
export const completeDeadline = async (deadlineId: string, options?: RequestInit): Promise<completeDeadlineResponse> => {

  return customInstance<completeDeadlineResponse>(getCompleteDeadlineUrl(deadlineId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCompleteDeadlineMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeDeadline>>, TError,{deadlineId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof completeDeadline>>, TError,{deadlineId: string}, TContext> => {

const mutationKey = ['completeDeadline'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeDeadline>>, {deadlineId: string}> = (props) => {
          const {deadlineId} = props ?? {};

          return  completeDeadline(deadlineId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteDeadlineMutationResult = NonNullable<Awaited<ReturnType<typeof completeDeadline>>>

    export type CompleteDeadlineMutationError = HTTPValidationError

    /**
 * @summary Complete Deadline
 */
export const useCompleteDeadline = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeDeadline>>, TError,{deadlineId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeDeadline>>,
        TError,
        {deadlineId: string},
        TContext
      > => {
      return useMutation(getCompleteDeadlineMutationOptions(options), queryClient);
    }
