"""add role enum

Revision ID: 07b5116bdc26
Revises: 2fa9a218fa75
Create Date: 2026-07-28 09:50:10.567046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b5116bdc26'
down_revision: Union[str, Sequence[str], None] = '2fa9a218fa75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Migrate existing roles to the new Enum values
    op.execute("UPDATE memberships SET role = 'FIRM_ADMIN' WHERE role IN ('admin', 'partner', 'FIRM_ADMIN')")
    op.execute("UPDATE memberships SET role = 'ATTORNEY' WHERE role IN ('lawyer', 'associate', 'ATTORNEY')")
    op.execute("UPDATE memberships SET role = 'READ_ONLY' WHERE role IN ('user', 'member', 'READ_ONLY')")
    # For any unknown roles, default them to READ_ONLY for safety
    op.execute("UPDATE memberships SET role = 'READ_ONLY' WHERE role NOT IN ('FIRM_ADMIN', 'ATTORNEY', 'PARALEGAL', 'READ_ONLY', 'AUDITOR', 'SUPPORT_TEMPORARY')")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
