"""matter_expansion

Revision ID: 08c0960c52ad
Revises: 1dc95c6dc781
Create Date: 2026-07-28 10:00:45.959299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c0960c52ad'
down_revision: Union[str, Sequence[str], None] = '1dc95c6dc781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matter_members',
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_scope', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_members_matter_id'), 'matter_members', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_members_tenant_id'), 'matter_members', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_matter_members_user_id'), 'matter_members', ['user_id'], unique=False)
    op.add_column('matters', sa.Column('jurisdiction', sa.String(), nullable=True))
    op.add_column('matters', sa.Column('confidentiality_level', sa.String(), server_default='standard', nullable=False))
    op.add_column('matters', sa.Column('lead_attorney_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'matters', 'users', ['lead_attorney_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matters', type_='foreignkey')
    op.drop_column('matters', 'lead_attorney_id')
    op.drop_column('matters', 'confidentiality_level')
    op.drop_column('matters', 'jurisdiction')
    op.drop_index(op.f('ix_matter_members_user_id'), table_name='matter_members')
    op.drop_index(op.f('ix_matter_members_tenant_id'), table_name='matter_members')
    op.drop_index(op.f('ix_matter_members_matter_id'), table_name='matter_members')
    op.drop_table('matter_members')
    # ### end Alembic commands ###
