"""Add Job and Outbox models

Revision ID: 130cbd278f22
Revises: 305d81551fce
Create Date: 2026-07-25 16:31:34.451584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130cbd278f22'
down_revision: Union[str, Sequence[str], None] = '305d81551fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_jobs',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_jobs_locked_until'), 'legal_jobs', ['locked_until'], unique=False)
    op.create_index(op.f('ix_legal_jobs_run_at'), 'legal_jobs', ['run_at'], unique=False)
    op.create_index(op.f('ix_legal_jobs_status'), 'legal_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_legal_jobs_type'), 'legal_jobs', ['type'], unique=False)
    op.create_table('legal_outbox',
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_outbox_event_type'), 'legal_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_legal_outbox_status'), 'legal_outbox', ['status'], unique=False)
    op.create_table('legal_job_attempts',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_details', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['legal_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_job_attempts_job_id'), 'legal_job_attempts', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_job_attempts_job_id'), table_name='legal_job_attempts')
    op.drop_table('legal_job_attempts')
    op.drop_index(op.f('ix_legal_outbox_status'), table_name='legal_outbox')
    op.drop_index(op.f('ix_legal_outbox_event_type'), table_name='legal_outbox')
    op.drop_table('legal_outbox')
    op.drop_index(op.f('ix_legal_jobs_type'), table_name='legal_jobs')
    op.drop_index(op.f('ix_legal_jobs_status'), table_name='legal_jobs')
    op.drop_index(op.f('ix_legal_jobs_run_at'), table_name='legal_jobs')
    op.drop_index(op.f('ix_legal_jobs_locked_until'), table_name='legal_jobs')
    op.drop_table('legal_jobs')
    # ### end Alembic commands ###
