"""Add draft model

Revision ID: 15b05b801f76
Revises: 2a7f34437d3e
Create Date: 2026-07-25 22:10:09.461297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b05b801f76'
down_revision: Union[str, Sequence[str], None] = '2a7f34437d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_matter_id'), 'drafts', ['matter_id'], unique=False)
    op.create_index(op.f('ix_drafts_tenant_id'), 'drafts', ['tenant_id'], unique=False)
    
    op.execute("ALTER TABLE drafts ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON drafts
        AS PERMISSIVE
        FOR ALL
        TO PUBLIC
        USING (tenant_id = current_setting('app.current_tenant', true))
        WITH CHECK (tenant_id = current_setting('app.current_tenant', true))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON drafts")
    op.execute("ALTER TABLE drafts DISABLE ROW LEVEL SECURITY")
    op.drop_index(op.f('ix_drafts_tenant_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_matter_id'), table_name='drafts')
    op.drop_table('drafts')
    # ### end Alembic commands ###
