"""Add review models

Revision ID: 15b7de04bc06
Revises: 5122f182a40b
Create Date: 2026-07-25 17:46:40.445695

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15b7de04bc06'
down_revision: str | Sequence[str] | None = '5122f182a40b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_audit_logs',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_audit_logs_matter_id'), 'legal_audit_logs', ['matter_id'], unique=False)
    op.create_index(op.f('ix_legal_audit_logs_tenant_id'), 'legal_audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_legal_audit_logs_user_id'), 'legal_audit_logs', ['user_id'], unique=False)
    op.create_table('legal_review_queue',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('proposed_content', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_use_ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corrected_content', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_review_queue_entity_id'), 'legal_review_queue', ['entity_id'], unique=False)
    op.create_index(op.f('ix_legal_review_queue_entity_type'), 'legal_review_queue', ['entity_type'], unique=False)
    op.create_index(op.f('ix_legal_review_queue_matter_id'), 'legal_review_queue', ['matter_id'], unique=False)
    op.create_index(op.f('ix_legal_review_queue_status'), 'legal_review_queue', ['status'], unique=False)
    op.create_index(op.f('ix_legal_review_queue_tenant_id'), 'legal_review_queue', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_review_queue_tenant_id'), table_name='legal_review_queue')
    op.drop_index(op.f('ix_legal_review_queue_status'), table_name='legal_review_queue')
    op.drop_index(op.f('ix_legal_review_queue_matter_id'), table_name='legal_review_queue')
    op.drop_index(op.f('ix_legal_review_queue_entity_type'), table_name='legal_review_queue')
    op.drop_index(op.f('ix_legal_review_queue_entity_id'), table_name='legal_review_queue')
    op.drop_table('legal_review_queue')
    op.drop_index(op.f('ix_legal_audit_logs_user_id'), table_name='legal_audit_logs')
    op.drop_index(op.f('ix_legal_audit_logs_tenant_id'), table_name='legal_audit_logs')
    op.drop_index(op.f('ix_legal_audit_logs_matter_id'), table_name='legal_audit_logs')
    op.drop_table('legal_audit_logs')
    # ### end Alembic commands ###
