"""Draft models updates for Phase 11

Revision ID: 17e0bd5dcd74
Revises: c4c0cf093982
Create Date: 2026-07-27 11:23:11.439812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e0bd5dcd74'
down_revision: Union[str, Sequence[str], None] = 'c4c0cf093982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_citations', sa.Column('draft_revision_id', sa.String(), nullable=True))
    op.add_column('draft_citations', sa.Column('document_id', sa.String(), nullable=True))
    op.add_column('draft_citations', sa.Column('document_revision_id', sa.String(), nullable=True))
    op.add_column('draft_citations', sa.Column('source_locator_id', sa.String(), nullable=True))
    op.add_column('draft_citations', sa.Column('verification_state', sa.String(), nullable=False))
    op.drop_index(op.f('ix_draft_citations_revision_id'), table_name='draft_citations')
    op.create_index(op.f('ix_draft_citations_draft_revision_id'), 'draft_citations', ['draft_revision_id'], unique=False)
    op.drop_constraint(op.f('draft_citations_revision_id_fkey'), 'draft_citations', type_='foreignkey')
    op.create_foreign_key(None, 'draft_citations', 'draft_revisions', ['draft_revision_id'], ['id'], ondelete='CASCADE')
    op.drop_column('draft_citations', 'source_entity_type')
    op.drop_column('draft_citations', 'revision_id')
    op.drop_column('draft_citations', 'source_entity_id')
    op.add_column('drafts', sa.Column('etag', sa.String(), nullable=False))
    op.add_column('drafts', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'status')
    op.drop_column('drafts', 'etag')
    op.add_column('draft_citations', sa.Column('source_entity_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('draft_citations', sa.Column('revision_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('draft_citations', sa.Column('source_entity_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'draft_citations', type_='foreignkey')
    op.create_foreign_key(op.f('draft_citations_revision_id_fkey'), 'draft_citations', 'draft_revisions', ['revision_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_draft_citations_draft_revision_id'), table_name='draft_citations')
    op.create_index(op.f('ix_draft_citations_revision_id'), 'draft_citations', ['revision_id'], unique=False)
    op.drop_column('draft_citations', 'verification_state')
    op.drop_column('draft_citations', 'source_locator_id')
    op.drop_column('draft_citations', 'document_revision_id')
    op.drop_column('draft_citations', 'document_id')
    op.drop_column('draft_citations', 'draft_revision_id')
    # ### end Alembic commands ###
