"""deadline_reliability

Revision ID: 26a9ead73cb5
Revises: 4c923ba03325
Create Date: 2026-07-28 10:04:16.277210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a9ead73cb5'
down_revision: Union[str, Sequence[str], None] = '4c923ba03325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approved_deadlines', sa.Column('timezone', sa.String(), server_default='Europe/Istanbul', nullable=False))
    op.add_column('deadline_candidates', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('deadline_candidates', sa.Column('timezone', sa.String(), server_default='Europe/Istanbul', nullable=False))
    
    deadline_state_enum = sa.Enum('POTENTIAL_DEADLINE', 'RULE_MATCHED', 'CALCULATED', 'ATTORNEY_VERIFIED', 'SCHEDULED', 'REJECTED', name='deadline_state')
    deadline_state_enum.create(op.get_bind())
    
    op.execute("ALTER TABLE deadline_candidates ALTER COLUMN status TYPE deadline_state USING status::deadline_state")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deadline_candidates', 'status',
               existing_type=sa.Enum('POTENTIAL_DEADLINE', 'RULE_MATCHED', 'CALCULATED', 'ATTORNEY_VERIFIED', 'SCHEDULED', 'REJECTED', name='deadline_state'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('deadline_candidates', 'timezone')
    op.drop_column('deadline_candidates', 'confidence_score')
    op.drop_column('approved_deadlines', 'timezone')
    # ### end Alembic commands ###
