"""Notifications schema update for Phase 12

Revision ID: 2fa9a218fa75
Revises: 17e0bd5dcd74
Create Date: 2026-07-27 11:24:09.979576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa9a218fa75'
down_revision: Union[str, Sequence[str], None] = '17e0bd5dcd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('category', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'category')
    # ### end Alembic commands ###
