"""legal_source_governance

Revision ID: 76f1d49b6552
Revises: 26a9ead73cb5
Create Date: 2026-07-28 10:05:15.585320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f1d49b6552'
down_revision: Union[str, Sequence[str], None] = '26a9ead73cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_assertions', sa.Column('legal_source_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_legal_assertions_legal_source_id'), 'legal_assertions', ['legal_source_id'], unique=False)
    op.create_foreign_key(None, 'legal_assertions', 'legal_sources', ['legal_source_id'], ['id'], ondelete='SET NULL')
    legal_source_status_enum = sa.Enum('CURRENT', 'STALE', 'SYNC_FAILED', 'LICENSE_RESTRICTED', 'SOURCE_UNAVAILABLE', name='legal_source_status')
    legal_source_status_enum.create(op.get_bind())
    
    op.execute("ALTER TABLE legal_sources ALTER COLUMN status TYPE legal_source_status USING status::legal_source_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('legal_sources', 'status',
               existing_type=sa.Enum('CURRENT', 'STALE', 'SYNC_FAILED', 'LICENSE_RESTRICTED', 'SOURCE_UNAVAILABLE', name='legal_source_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'legal_assertions', type_='foreignkey')
    op.drop_index(op.f('ix_legal_assertions_legal_source_id'), table_name='legal_assertions')
    op.drop_column('legal_assertions', 'legal_source_id')
    # ### end Alembic commands ###
