"""Add source_locator_id to canonical entities

Revision ID: c150029e598e
Revises: fc0d8a50b082
Create Date: 2026-07-28 16:57:59.295513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c150029e598e'
down_revision: Union[str, Sequence[str], None] = 'fc0d8a50b082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('source_locator_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_claims_source_locator_id'), 'claims', ['source_locator_id'], unique=False)
    op.create_foreign_key(None, 'claims', 'source_locators', ['source_locator_id'], ['id'], ondelete='SET NULL')
    op.add_column('evidence_items', sa.Column('source_locator_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_evidence_items_source_locator_id'), 'evidence_items', ['source_locator_id'], unique=False)
    op.create_foreign_key(None, 'evidence_items', 'source_locators', ['source_locator_id'], ['id'], ondelete='SET NULL')
    op.add_column('matter_parties', sa.Column('source_locator_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_matter_parties_source_locator_id'), 'matter_parties', ['source_locator_id'], unique=False)
    op.create_foreign_key(None, 'matter_parties', 'source_locators', ['source_locator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matter_parties', type_='foreignkey')
    op.drop_index(op.f('ix_matter_parties_source_locator_id'), table_name='matter_parties')
    op.drop_column('matter_parties', 'source_locator_id')
    op.drop_constraint(None, 'evidence_items', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_items_source_locator_id'), table_name='evidence_items')
    op.drop_column('evidence_items', 'source_locator_id')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_index(op.f('ix_claims_source_locator_id'), table_name='claims')
    op.drop_column('claims', 'source_locator_id')
    # ### end Alembic commands ###
