"""Update deadline models to match Phase 10

Revision ID: c4c0cf093982
Revises: 850990b05edc
Create Date: 2026-07-27 11:20:31.233303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c0cf093982'
down_revision: Union[str, Sequence[str], None] = '850990b05edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline_rule_packs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('holiday_calendars',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('dates', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('deadline_candidates',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('calculated_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['deadline_rules.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadline_candidates_matter_id'), 'deadline_candidates', ['matter_id'], unique=False)
    op.create_index(op.f('ix_deadline_candidates_tenant_id'), 'deadline_candidates', ['tenant_id'], unique=False)
    op.add_column('approved_deadlines', sa.Column('deadline_candidate_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('approved_deadlines_potential_deadline_id_fkey'), 'approved_deadlines', type_='foreignkey')
    op.create_foreign_key(None, 'approved_deadlines', 'deadline_candidates', ['deadline_candidate_id'], ['id'])
    op.drop_column('approved_deadlines', 'potential_deadline_id')
    op.add_column('deadline_rules', sa.Column('jurisdiction', sa.String(), nullable=True))
    op.add_column('deadline_rules', sa.Column('procedure_type', sa.String(), nullable=True))
    op.add_column('deadline_rules', sa.Column('trigger_type', sa.String(), nullable=False))
    op.add_column('deadline_rules', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('deadline_rules', sa.Column('duration_unit', sa.String(), nullable=False))
    op.add_column('deadline_rules', sa.Column('calculation_method', sa.String(), nullable=False))
    op.add_column('deadline_rules', sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deadline_rules', sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deadline_rules', sa.Column('legal_source_id', sa.String(), nullable=True))
    op.add_column('deadline_rules', sa.Column('holiday_calendar_version', sa.String(), nullable=True))
    op.add_column('deadline_rules', sa.Column('reviewed_by', sa.String(), nullable=True))
    op.add_column('deadline_rules', sa.Column('rule_pack_version', sa.String(), nullable=True))
    op.create_foreign_key(None, 'deadline_rules', 'legal_sources', ['legal_source_id'], ['id'])
    op.drop_column('deadline_rules', 'offset_days')
    op.drop_column('deadline_rules', 'trigger_event')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadline_rules', sa.Column('trigger_event', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('deadline_rules', sa.Column('offset_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deadline_rules', type_='foreignkey')
    op.drop_column('deadline_rules', 'rule_pack_version')
    op.drop_column('deadline_rules', 'reviewed_by')
    op.drop_column('deadline_rules', 'holiday_calendar_version')
    op.drop_column('deadline_rules', 'legal_source_id')
    op.drop_column('deadline_rules', 'effective_to')
    op.drop_column('deadline_rules', 'effective_from')
    op.drop_column('deadline_rules', 'calculation_method')
    op.drop_column('deadline_rules', 'duration_unit')
    op.drop_column('deadline_rules', 'duration')
    op.drop_column('deadline_rules', 'trigger_type')
    op.drop_column('deadline_rules', 'procedure_type')
    op.drop_column('deadline_rules', 'jurisdiction')
    op.add_column('approved_deadlines', sa.Column('potential_deadline_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'approved_deadlines', type_='foreignkey')
    op.create_foreign_key(op.f('approved_deadlines_potential_deadline_id_fkey'), 'approved_deadlines', 'potential_deadlines', ['potential_deadline_id'], ['id'])
    op.drop_column('approved_deadlines', 'deadline_candidate_id')
    op.drop_index(op.f('ix_deadline_candidates_tenant_id'), table_name='deadline_candidates')
    op.drop_index(op.f('ix_deadline_candidates_matter_id'), table_name='deadline_candidates')
    op.drop_table('deadline_candidates')
    op.drop_table('holiday_calendars')
    op.drop_table('deadline_rule_packs')
    # ### end Alembic commands ###
