"""Add tenant_id to jobs

Revision ID: f375feb1c23f
Revises: 7d03c6f46165
Create Date: 2026-07-28 16:15:55.592600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f375feb1c23f'
down_revision: Union[str, Sequence[str], None] = '7d03c6f46165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_jobs', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('legal_jobs', sa.Column('matter_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_legal_jobs_matter_id'), 'legal_jobs', ['matter_id'], unique=False)
    op.create_index(op.f('ix_legal_jobs_tenant_id'), 'legal_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_jobs_tenant_id'), table_name='legal_jobs')
    op.drop_index(op.f('ix_legal_jobs_matter_id'), table_name='legal_jobs')
    op.drop_column('legal_jobs', 'matter_id')
    op.drop_column('legal_jobs', 'tenant_id')
    # ### end Alembic commands ###
