"""Add provenance fields and tenant_id

Revision ID: f5d27f07a1d3
Revises: c352dad29efc
Create Date: 2026-07-27 11:10:55.675315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d27f07a1d3'
down_revision: Union[str, Sequence[str], None] = 'c352dad29efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_revisions', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_document_revisions_tenant_id'), 'document_revisions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'document_revisions', 'firms', ['tenant_id'], ['id'])
    op.add_column('parsed_documents', sa.Column('ocr_version', sa.String(), nullable=True))
    op.add_column('parsed_documents', sa.Column('pipeline_version', sa.String(), nullable=True))
    op.add_column('parsed_documents', sa.Column('input_hash', sa.String(), nullable=True))
    op.add_column('parsed_documents', sa.Column('output_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_documents', 'output_hash')
    op.drop_column('parsed_documents', 'input_hash')
    op.drop_column('parsed_documents', 'pipeline_version')
    op.drop_column('parsed_documents', 'ocr_version')
    op.drop_constraint(None, 'document_revisions', type_='foreignkey')
    op.drop_index(op.f('ix_document_revisions_tenant_id'), table_name='document_revisions')
    op.drop_column('document_revisions', 'tenant_id')
    # ### end Alembic commands ###
