/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  LegalSourceResponse,
  ResearchRequest,
  SearchLegalResearchParams
} from '../../models';

import { customInstance } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type startLegalResearchResponse200 = {
  data: unknown
  status: 200
}

export type startLegalResearchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type startLegalResearchResponseSuccess = (startLegalResearchResponse200) & {
  headers: Headers;
};
export type startLegalResearchResponseError = (startLegalResearchResponse422) & {
  headers: Headers;
};

export type startLegalResearchResponse = (startLegalResearchResponseSuccess | startLegalResearchResponseError)

export const getStartLegalResearchUrl = () => {




  return `/api/v1/research/start`
}

/**
 * @summary Start Legal Research
 */
export const startLegalResearch = async (researchRequest: ResearchRequest, options?: RequestInit): Promise<startLegalResearchResponse> => {

  return customInstance<startLegalResearchResponse>(getStartLegalResearchUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(researchRequest)
  }
);}





export const getStartLegalResearchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startLegalResearch>>, TError,{data: ResearchRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startLegalResearch>>, TError,{data: ResearchRequest}, TContext> => {

const mutationKey = ['startLegalResearch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startLegalResearch>>, {data: ResearchRequest}> = (props) => {
          const {data} = props ?? {};

          return  startLegalResearch(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartLegalResearchMutationResult = NonNullable<Awaited<ReturnType<typeof startLegalResearch>>>
    export type StartLegalResearchMutationBody = ResearchRequest
    export type StartLegalResearchMutationError = HTTPValidationError

    /**
 * @summary Start Legal Research
 */
export const useStartLegalResearch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startLegalResearch>>, TError,{data: ResearchRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startLegalResearch>>,
        TError,
        {data: ResearchRequest},
        TContext
      > => {
      return useMutation(getStartLegalResearchMutationOptions(options), queryClient);
    }
    export type searchLegalResearchResponse200 = {
  data: LegalSourceResponse[]
  status: 200
}

export type searchLegalResearchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type searchLegalResearchResponseSuccess = (searchLegalResearchResponse200) & {
  headers: Headers;
};
export type searchLegalResearchResponseError = (searchLegalResearchResponse422) & {
  headers: Headers;
};

export type searchLegalResearchResponse = (searchLegalResearchResponseSuccess | searchLegalResearchResponseError)

export const getSearchLegalResearchUrl = (params: SearchLegalResearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/research/search?${stringifiedParams}` : `/api/v1/research/search`
}

/**
 * @summary Search Legal Research
 */
export const searchLegalResearch = async (params: SearchLegalResearchParams, options?: RequestInit): Promise<searchLegalResearchResponse> => {

  return customInstance<searchLegalResearchResponse>(getSearchLegalResearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSearchLegalResearchQueryKey = (params?: SearchLegalResearchParams,) => {
    return [
    `/api/v1/research/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchLegalResearchQueryOptions = <TData = Awaited<ReturnType<typeof searchLegalResearch>>, TError = HTTPValidationError>(params: SearchLegalResearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLegalResearch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchLegalResearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchLegalResearch>>> = ({ signal }) => searchLegalResearch(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchLegalResearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchLegalResearchQueryResult = NonNullable<Awaited<ReturnType<typeof searchLegalResearch>>>
export type SearchLegalResearchQueryError = HTTPValidationError


export function useSearchLegalResearch<TData = Awaited<ReturnType<typeof searchLegalResearch>>, TError = HTTPValidationError>(
 params: SearchLegalResearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLegalResearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchLegalResearch>>,
          TError,
          Awaited<ReturnType<typeof searchLegalResearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchLegalResearch<TData = Awaited<ReturnType<typeof searchLegalResearch>>, TError = HTTPValidationError>(
 params: SearchLegalResearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLegalResearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchLegalResearch>>,
          TError,
          Awaited<ReturnType<typeof searchLegalResearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchLegalResearch<TData = Awaited<ReturnType<typeof searchLegalResearch>>, TError = HTTPValidationError>(
 params: SearchLegalResearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLegalResearch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search Legal Research
 */

export function useSearchLegalResearch<TData = Awaited<ReturnType<typeof searchLegalResearch>>, TError = HTTPValidationError>(
 params: SearchLegalResearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLegalResearch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchLegalResearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






