/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '../../models';

import { customInstance } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getDashboardMetricsApiV1DashboardMetricsGetResponse200 = {
  data: unknown
  status: 200
}

export type getDashboardMetricsApiV1DashboardMetricsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getDashboardMetricsApiV1DashboardMetricsGetResponseSuccess = (getDashboardMetricsApiV1DashboardMetricsGetResponse200) & {
  headers: Headers;
};
export type getDashboardMetricsApiV1DashboardMetricsGetResponseError = (getDashboardMetricsApiV1DashboardMetricsGetResponse422) & {
  headers: Headers;
};

export type getDashboardMetricsApiV1DashboardMetricsGetResponse = (getDashboardMetricsApiV1DashboardMetricsGetResponseSuccess | getDashboardMetricsApiV1DashboardMetricsGetResponseError)

export const getGetDashboardMetricsApiV1DashboardMetricsGetUrl = () => {




  return `/api/v1/dashboard/metrics`
}

/**
 * @summary Get Dashboard Metrics
 */
export const getDashboardMetricsApiV1DashboardMetricsGet = async ( options?: RequestInit): Promise<getDashboardMetricsApiV1DashboardMetricsGetResponse> => {

  return customInstance<getDashboardMetricsApiV1DashboardMetricsGetResponse>(getGetDashboardMetricsApiV1DashboardMetricsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardMetricsApiV1DashboardMetricsGetQueryKey = () => {
    return [
    `/api/v1/dashboard/metrics`
    ] as const;
    }


export const getGetDashboardMetricsApiV1DashboardMetricsGetQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardMetricsApiV1DashboardMetricsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>> = ({ signal }) => getDashboardMetricsApiV1DashboardMetricsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardMetricsApiV1DashboardMetricsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>>
export type GetDashboardMetricsApiV1DashboardMetricsGetQueryError = HTTPValidationError


export function useGetDashboardMetricsApiV1DashboardMetricsGet<TData = Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>,
          TError,
          Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardMetricsApiV1DashboardMetricsGet<TData = Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>,
          TError,
          Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardMetricsApiV1DashboardMetricsGet<TData = Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Dashboard Metrics
 */

export function useGetDashboardMetricsApiV1DashboardMetricsGet<TData = Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardMetricsApiV1DashboardMetricsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardMetricsApiV1DashboardMetricsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






