/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DocumentResponse,
  HTTPValidationError,
  MatterCreate,
  MatterResponse,
  UploadIntentRequest,
  UploadIntentResponse
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listMattersResponse200 = {
  data: MatterResponse[]
  status: 200
}

export type listMattersResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listMattersResponseSuccess = (listMattersResponse200) & {
  headers: Headers;
};
export type listMattersResponseError = (listMattersResponse422) & {
  headers: Headers;
};

export type listMattersResponse = (listMattersResponseSuccess | listMattersResponseError)

export const getListMattersUrl = () => {




  return `/api/matters`
}

/**
 * @summary List Matters
 */
export const listMatters = async ( options?: RequestInit): Promise<listMattersResponse> => {

  return customInstance<listMattersResponse>(getListMattersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMattersQueryKey = () => {
    return [
    `/api/matters`
    ] as const;
    }


export const getListMattersQueryOptions = <TData = Awaited<ReturnType<typeof listMatters>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMattersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMatters>>> = ({ signal }) => listMatters({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMattersQueryResult = NonNullable<Awaited<ReturnType<typeof listMatters>>>
export type ListMattersQueryError = HTTPValidationError


export function useListMatters<TData = Awaited<ReturnType<typeof listMatters>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatters>>,
          TError,
          Awaited<ReturnType<typeof listMatters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatters<TData = Awaited<ReturnType<typeof listMatters>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatters>>,
          TError,
          Awaited<ReturnType<typeof listMatters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatters<TData = Awaited<ReturnType<typeof listMatters>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Matters
 */

export function useListMatters<TData = Awaited<ReturnType<typeof listMatters>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMattersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createMatterResponse200 = {
  data: MatterResponse
  status: 200
}

export type createMatterResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createMatterResponseSuccess = (createMatterResponse200) & {
  headers: Headers;
};
export type createMatterResponseError = (createMatterResponse422) & {
  headers: Headers;
};

export type createMatterResponse = (createMatterResponseSuccess | createMatterResponseError)

export const getCreateMatterUrl = () => {




  return `/api/matters`
}

/**
 * @summary Create Matter
 */
export const createMatter = async (matterCreate: MatterCreate, options?: RequestInit): Promise<createMatterResponse> => {

  return customInstance<createMatterResponse>(getCreateMatterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matterCreate)
  }
);}





export const getCreateMatterMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMatter>>, TError,{data: MatterCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createMatter>>, TError,{data: MatterCreate}, TContext> => {

const mutationKey = ['createMatter'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMatter>>, {data: MatterCreate}> = (props) => {
          const {data} = props ?? {};

          return  createMatter(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMatterMutationResult = NonNullable<Awaited<ReturnType<typeof createMatter>>>
    export type CreateMatterMutationBody = MatterCreate
    export type CreateMatterMutationError = HTTPValidationError

    /**
 * @summary Create Matter
 */
export const useCreateMatter = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMatter>>, TError,{data: MatterCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMatter>>,
        TError,
        {data: MatterCreate},
        TContext
      > => {
      return useMutation(getCreateMatterMutationOptions(options), queryClient);
    }
    export type createUploadIntentResponse200 = {
  data: UploadIntentResponse
  status: 200
}

export type createUploadIntentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createUploadIntentResponseSuccess = (createUploadIntentResponse200) & {
  headers: Headers;
};
export type createUploadIntentResponseError = (createUploadIntentResponse422) & {
  headers: Headers;
};

export type createUploadIntentResponse = (createUploadIntentResponseSuccess | createUploadIntentResponseError)

export const getCreateUploadIntentUrl = () => {




  return `/api/documents/upload-intent`
}

/**
 * @summary Create Upload Intent
 */
export const createUploadIntent = async (uploadIntentRequest: UploadIntentRequest, options?: RequestInit): Promise<createUploadIntentResponse> => {

  return customInstance<createUploadIntentResponse>(getCreateUploadIntentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(uploadIntentRequest)
  }
);}





export const getCreateUploadIntentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUploadIntent>>, TError,{data: UploadIntentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createUploadIntent>>, TError,{data: UploadIntentRequest}, TContext> => {

const mutationKey = ['createUploadIntent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUploadIntent>>, {data: UploadIntentRequest}> = (props) => {
          const {data} = props ?? {};

          return  createUploadIntent(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUploadIntentMutationResult = NonNullable<Awaited<ReturnType<typeof createUploadIntent>>>
    export type CreateUploadIntentMutationBody = UploadIntentRequest
    export type CreateUploadIntentMutationError = HTTPValidationError

    /**
 * @summary Create Upload Intent
 */
export const useCreateUploadIntent = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUploadIntent>>, TError,{data: UploadIntentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUploadIntent>>,
        TError,
        {data: UploadIntentRequest},
        TContext
      > => {
      return useMutation(getCreateUploadIntentMutationOptions(options), queryClient);
    }
    export type listDocumentsResponse200 = {
  data: DocumentResponse[]
  status: 200
}

export type listDocumentsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listDocumentsResponseSuccess = (listDocumentsResponse200) & {
  headers: Headers;
};
export type listDocumentsResponseError = (listDocumentsResponse422) & {
  headers: Headers;
};

export type listDocumentsResponse = (listDocumentsResponseSuccess | listDocumentsResponseError)

export const getListDocumentsUrl = (matterId: string,) => {




  return `/api/matters/${matterId}/documents`
}

/**
 * @summary List Documents
 */
export const listDocuments = async (matterId: string, options?: RequestInit): Promise<listDocumentsResponse> => {

  return customInstance<listDocumentsResponse>(getListDocumentsUrl(matterId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDocumentsQueryKey = (matterId: string,) => {
    return [
    `/api/matters/${matterId}/documents`
    ] as const;
    }


export const getListDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof listDocuments>>, TError = HTTPValidationError>(matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDocumentsQueryKey(matterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDocuments>>> = ({ signal }) => listDocuments(matterId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: matterId !== null && matterId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listDocuments>>>
export type ListDocumentsQueryError = HTTPValidationError


export function useListDocuments<TData = Awaited<ReturnType<typeof listDocuments>>, TError = HTTPValidationError>(
 matterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDocuments>>,
          TError,
          Awaited<ReturnType<typeof listDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDocuments<TData = Awaited<ReturnType<typeof listDocuments>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDocuments>>,
          TError,
          Awaited<ReturnType<typeof listDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDocuments<TData = Awaited<ReturnType<typeof listDocuments>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Documents
 */

export function useListDocuments<TData = Awaited<ReturnType<typeof listDocuments>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDocumentsQueryOptions(matterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






