/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConflictCheckRequest,
  ConflictCheckResponse,
  DocumentResponse,
  ElevateRoleParams,
  FirmCreateRequest,
  FirmResponse,
  HTTPValidationError,
  MatterCreate,
  MatterQABody,
  MatterResponse,
  OverrideConflictParams,
  OverrideConflictRequest,
  ParsedDocumentResponse,
  ParsedPageResponse,
  RoleElevationRequest,
  UploadIntentRequest,
  UploadIntentResponse
} from '../../models';

import { customInstance } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listUserFirmsResponse200 = {
  data: FirmResponse[]
  status: 200
}

export type listUserFirmsResponseSuccess = (listUserFirmsResponse200) & {
  headers: Headers;
};
;

export type listUserFirmsResponse = (listUserFirmsResponseSuccess)

export const getListUserFirmsUrl = () => {




  return `/api/v1/firms`
}

/**
 * @summary List User Firms
 */
export const listUserFirms = async ( options?: RequestInit): Promise<listUserFirmsResponse> => {

  return customInstance<listUserFirmsResponse>(getListUserFirmsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListUserFirmsQueryKey = () => {
    return [
    `/api/v1/firms`
    ] as const;
    }


export const getListUserFirmsQueryOptions = <TData = Awaited<ReturnType<typeof listUserFirms>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserFirms>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUserFirmsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUserFirms>>> = ({ signal }) => listUserFirms({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUserFirms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUserFirmsQueryResult = NonNullable<Awaited<ReturnType<typeof listUserFirms>>>
export type ListUserFirmsQueryError = unknown


export function useListUserFirms<TData = Awaited<ReturnType<typeof listUserFirms>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserFirms>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserFirms>>,
          TError,
          Awaited<ReturnType<typeof listUserFirms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUserFirms<TData = Awaited<ReturnType<typeof listUserFirms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserFirms>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserFirms>>,
          TError,
          Awaited<ReturnType<typeof listUserFirms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUserFirms<TData = Awaited<ReturnType<typeof listUserFirms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserFirms>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List User Firms
 */

export function useListUserFirms<TData = Awaited<ReturnType<typeof listUserFirms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserFirms>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUserFirmsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createFirmResponse200 = {
  data: FirmResponse
  status: 200
}

export type createFirmResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createFirmResponseSuccess = (createFirmResponse200) & {
  headers: Headers;
};
export type createFirmResponseError = (createFirmResponse422) & {
  headers: Headers;
};

export type createFirmResponse = (createFirmResponseSuccess | createFirmResponseError)

export const getCreateFirmUrl = () => {




  return `/api/v1/firms`
}

/**
 * @summary Create Firm
 */
export const createFirm = async (firmCreateRequest: FirmCreateRequest, options?: RequestInit): Promise<createFirmResponse> => {

  return customInstance<createFirmResponse>(getCreateFirmUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(firmCreateRequest)
  }
);}





export const getCreateFirmMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFirm>>, TError,{data: FirmCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createFirm>>, TError,{data: FirmCreateRequest}, TContext> => {

const mutationKey = ['createFirm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFirm>>, {data: FirmCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createFirm(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFirmMutationResult = NonNullable<Awaited<ReturnType<typeof createFirm>>>
    export type CreateFirmMutationBody = FirmCreateRequest
    export type CreateFirmMutationError = HTTPValidationError

    /**
 * @summary Create Firm
 */
export const useCreateFirm = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFirm>>, TError,{data: FirmCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFirm>>,
        TError,
        {data: FirmCreateRequest},
        TContext
      > => {
      return useMutation(getCreateFirmMutationOptions(options), queryClient);
    }
    export type listFirmMembersResponse200 = {
  data: unknown
  status: 200
}

export type listFirmMembersResponseSuccess = (listFirmMembersResponse200) & {
  headers: Headers;
};
;

export type listFirmMembersResponse = (listFirmMembersResponseSuccess)

export const getListFirmMembersUrl = () => {




  return `/api/v1/firms/members`
}

/**
 * @summary List Firm Members
 */
export const listFirmMembers = async ( options?: RequestInit): Promise<listFirmMembersResponse> => {

  return customInstance<listFirmMembersResponse>(getListFirmMembersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFirmMembersQueryKey = () => {
    return [
    `/api/v1/firms/members`
    ] as const;
    }


export const getListFirmMembersQueryOptions = <TData = Awaited<ReturnType<typeof listFirmMembers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFirmMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFirmMembersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFirmMembers>>> = ({ signal }) => listFirmMembers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFirmMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFirmMembersQueryResult = NonNullable<Awaited<ReturnType<typeof listFirmMembers>>>
export type ListFirmMembersQueryError = unknown


export function useListFirmMembers<TData = Awaited<ReturnType<typeof listFirmMembers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFirmMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFirmMembers>>,
          TError,
          Awaited<ReturnType<typeof listFirmMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFirmMembers<TData = Awaited<ReturnType<typeof listFirmMembers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFirmMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFirmMembers>>,
          TError,
          Awaited<ReturnType<typeof listFirmMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFirmMembers<TData = Awaited<ReturnType<typeof listFirmMembers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFirmMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Firm Members
 */

export function useListFirmMembers<TData = Awaited<ReturnType<typeof listFirmMembers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFirmMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFirmMembersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getFirmDetailsResponse200 = {
  data: FirmResponse
  status: 200
}

export type getFirmDetailsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getFirmDetailsResponseSuccess = (getFirmDetailsResponse200) & {
  headers: Headers;
};
export type getFirmDetailsResponseError = (getFirmDetailsResponse422) & {
  headers: Headers;
};

export type getFirmDetailsResponse = (getFirmDetailsResponseSuccess | getFirmDetailsResponseError)

export const getGetFirmDetailsUrl = (firmId: string,) => {




  return `/api/v1/firms/${firmId}`
}

/**
 * @summary Get Firm Details
 */
export const getFirmDetails = async (firmId: string, options?: RequestInit): Promise<getFirmDetailsResponse> => {

  return customInstance<getFirmDetailsResponse>(getGetFirmDetailsUrl(firmId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFirmDetailsQueryKey = (firmId: string,) => {
    return [
    `/api/v1/firms/${firmId}`
    ] as const;
    }


export const getGetFirmDetailsQueryOptions = <TData = Awaited<ReturnType<typeof getFirmDetails>>, TError = HTTPValidationError>(firmId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFirmDetails>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFirmDetailsQueryKey(firmId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFirmDetails>>> = ({ signal }) => getFirmDetails(firmId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: firmId !== null && firmId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFirmDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFirmDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof getFirmDetails>>>
export type GetFirmDetailsQueryError = HTTPValidationError


export function useGetFirmDetails<TData = Awaited<ReturnType<typeof getFirmDetails>>, TError = HTTPValidationError>(
 firmId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFirmDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFirmDetails>>,
          TError,
          Awaited<ReturnType<typeof getFirmDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFirmDetails<TData = Awaited<ReturnType<typeof getFirmDetails>>, TError = HTTPValidationError>(
 firmId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFirmDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFirmDetails>>,
          TError,
          Awaited<ReturnType<typeof getFirmDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFirmDetails<TData = Awaited<ReturnType<typeof getFirmDetails>>, TError = HTTPValidationError>(
 firmId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFirmDetails>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Firm Details
 */

export function useGetFirmDetails<TData = Awaited<ReturnType<typeof getFirmDetails>>, TError = HTTPValidationError>(
 firmId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFirmDetails>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFirmDetailsQueryOptions(firmId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type elevateRoleResponse200 = {
  data: unknown
  status: 200
}

export type elevateRoleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type elevateRoleResponseSuccess = (elevateRoleResponse200) & {
  headers: Headers;
};
export type elevateRoleResponseError = (elevateRoleResponse422) & {
  headers: Headers;
};

export type elevateRoleResponse = (elevateRoleResponseSuccess | elevateRoleResponseError)

export const getElevateRoleUrl = (firmId: string,
    userId: string,
    params?: ElevateRoleParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/firms/${firmId}/members/${userId}/role?${stringifiedParams}` : `/api/v1/firms/${firmId}/members/${userId}/role`
}

/**
 * @summary Elevate Role
 */
export const elevateRole = async (firmId: string,
    userId: string,
    roleElevationRequest: RoleElevationRequest,
    params?: ElevateRoleParams, options?: RequestInit): Promise<elevateRoleResponse> => {

  return customInstance<elevateRoleResponse>(getElevateRoleUrl(firmId,userId,params),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(roleElevationRequest)
  }
);}





export const getElevateRoleMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof elevateRole>>, TError,{firmId: string;userId: string;data: RoleElevationRequest;params?: ElevateRoleParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof elevateRole>>, TError,{firmId: string;userId: string;data: RoleElevationRequest;params?: ElevateRoleParams}, TContext> => {

const mutationKey = ['elevateRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof elevateRole>>, {firmId: string;userId: string;data: RoleElevationRequest;params?: ElevateRoleParams}> = (props) => {
          const {firmId,userId,data,params} = props ?? {};

          return  elevateRole(firmId,userId,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ElevateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof elevateRole>>>
    export type ElevateRoleMutationBody = RoleElevationRequest
    export type ElevateRoleMutationError = HTTPValidationError

    /**
 * @summary Elevate Role
 */
export const useElevateRole = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof elevateRole>>, TError,{firmId: string;userId: string;data: RoleElevationRequest;params?: ElevateRoleParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof elevateRole>>,
        TError,
        {firmId: string;userId: string;data: RoleElevationRequest;params?: ElevateRoleParams},
        TContext
      > => {
      return useMutation(getElevateRoleMutationOptions(options), queryClient);
    }
    export type listMattersResponse200 = {
  data: MatterResponse[]
  status: 200
}

export type listMattersResponseSuccess = (listMattersResponse200) & {
  headers: Headers;
};
;

export type listMattersResponse = (listMattersResponseSuccess)

export const getListMattersUrl = () => {




  return `/api/v1/matters`
}

/**
 * @summary List Matters
 */
export const listMatters = async ( options?: RequestInit): Promise<listMattersResponse> => {

  return customInstance<listMattersResponse>(getListMattersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMattersQueryKey = () => {
    return [
    `/api/v1/matters`
    ] as const;
    }


export const getListMattersQueryOptions = <TData = Awaited<ReturnType<typeof listMatters>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMattersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMatters>>> = ({ signal }) => listMatters({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMattersQueryResult = NonNullable<Awaited<ReturnType<typeof listMatters>>>
export type ListMattersQueryError = unknown


export function useListMatters<TData = Awaited<ReturnType<typeof listMatters>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatters>>,
          TError,
          Awaited<ReturnType<typeof listMatters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatters<TData = Awaited<ReturnType<typeof listMatters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatters>>,
          TError,
          Awaited<ReturnType<typeof listMatters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatters<TData = Awaited<ReturnType<typeof listMatters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Matters
 */

export function useListMatters<TData = Awaited<ReturnType<typeof listMatters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMattersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createMatterResponse201 = {
  data: MatterResponse
  status: 201
}

export type createMatterResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createMatterResponseSuccess = (createMatterResponse201) & {
  headers: Headers;
};
export type createMatterResponseError = (createMatterResponse422) & {
  headers: Headers;
};

export type createMatterResponse = (createMatterResponseSuccess | createMatterResponseError)

export const getCreateMatterUrl = () => {




  return `/api/v1/matters`
}

/**
 * @summary Create Matter
 */
export const createMatter = async (matterCreate: MatterCreate, options?: RequestInit): Promise<createMatterResponse> => {

  return customInstance<createMatterResponse>(getCreateMatterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matterCreate)
  }
);}





export const getCreateMatterMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMatter>>, TError,{data: MatterCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createMatter>>, TError,{data: MatterCreate}, TContext> => {

const mutationKey = ['createMatter'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMatter>>, {data: MatterCreate}> = (props) => {
          const {data} = props ?? {};

          return  createMatter(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMatterMutationResult = NonNullable<Awaited<ReturnType<typeof createMatter>>>
    export type CreateMatterMutationBody = MatterCreate
    export type CreateMatterMutationError = HTTPValidationError

    /**
 * @summary Create Matter
 */
export const useCreateMatter = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMatter>>, TError,{data: MatterCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMatter>>,
        TError,
        {data: MatterCreate},
        TContext
      > => {
      return useMutation(getCreateMatterMutationOptions(options), queryClient);
    }
    export type rebuildMatterMesaResponse200 = {
  data: unknown
  status: 200
}

export type rebuildMatterMesaResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type rebuildMatterMesaResponseSuccess = (rebuildMatterMesaResponse200) & {
  headers: Headers;
};
export type rebuildMatterMesaResponseError = (rebuildMatterMesaResponse422) & {
  headers: Headers;
};

export type rebuildMatterMesaResponse = (rebuildMatterMesaResponseSuccess | rebuildMatterMesaResponseError)

export const getRebuildMatterMesaUrl = (matterId: string,) => {




  return `/api/v1/matters/${matterId}/rebuild-mesa`
}

/**
 * @summary Rebuild Matter Mesa
 */
export const rebuildMatterMesa = async (matterId: string, options?: RequestInit): Promise<rebuildMatterMesaResponse> => {

  return customInstance<rebuildMatterMesaResponse>(getRebuildMatterMesaUrl(matterId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getRebuildMatterMesaMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rebuildMatterMesa>>, TError,{matterId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof rebuildMatterMesa>>, TError,{matterId: string}, TContext> => {

const mutationKey = ['rebuildMatterMesa'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rebuildMatterMesa>>, {matterId: string}> = (props) => {
          const {matterId} = props ?? {};

          return  rebuildMatterMesa(matterId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RebuildMatterMesaMutationResult = NonNullable<Awaited<ReturnType<typeof rebuildMatterMesa>>>

    export type RebuildMatterMesaMutationError = HTTPValidationError

    /**
 * @summary Rebuild Matter Mesa
 */
export const useRebuildMatterMesa = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rebuildMatterMesa>>, TError,{matterId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rebuildMatterMesa>>,
        TError,
        {matterId: string},
        TContext
      > => {
      return useMutation(getRebuildMatterMesaMutationOptions(options), queryClient);
    }
    export type matterQAResponse200 = {
  data: unknown
  status: 200
}

export type matterQAResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type matterQAResponseSuccess = (matterQAResponse200) & {
  headers: Headers;
};
export type matterQAResponseError = (matterQAResponse422) & {
  headers: Headers;
};

export type matterQAResponse = (matterQAResponseSuccess | matterQAResponseError)

export const getMatterQAUrl = (matterId: string,) => {




  return `/api/v1/matters/${matterId}/qa`
}

/**
 * @summary Matter Qa Endpoint
 */
export const matterQA = async (matterId: string,
    matterQABody: MatterQABody, options?: RequestInit): Promise<matterQAResponse> => {

  return customInstance<matterQAResponse>(getMatterQAUrl(matterId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matterQABody)
  }
);}





export const getMatterQAMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof matterQA>>, TError,{matterId: string;data: MatterQABody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof matterQA>>, TError,{matterId: string;data: MatterQABody}, TContext> => {

const mutationKey = ['matterQA'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof matterQA>>, {matterId: string;data: MatterQABody}> = (props) => {
          const {matterId,data} = props ?? {};

          return  matterQA(matterId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MatterQAMutationResult = NonNullable<Awaited<ReturnType<typeof matterQA>>>
    export type MatterQAMutationBody = MatterQABody
    export type MatterQAMutationError = HTTPValidationError

    /**
 * @summary Matter Qa Endpoint
 */
export const useMatterQA = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof matterQA>>, TError,{matterId: string;data: MatterQABody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof matterQA>>,
        TError,
        {matterId: string;data: MatterQABody},
        TContext
      > => {
      return useMutation(getMatterQAMutationOptions(options), queryClient);
    }
    export type conflictCheckResponse200 = {
  data: ConflictCheckResponse
  status: 200
}

export type conflictCheckResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type conflictCheckResponseSuccess = (conflictCheckResponse200) & {
  headers: Headers;
};
export type conflictCheckResponseError = (conflictCheckResponse422) & {
  headers: Headers;
};

export type conflictCheckResponse = (conflictCheckResponseSuccess | conflictCheckResponseError)

export const getConflictCheckUrl = () => {




  return `/api/v1/matters/conflict-check`
}

/**
 * @summary Check Conflicts
 */
export const conflictCheck = async (conflictCheckRequest: ConflictCheckRequest, options?: RequestInit): Promise<conflictCheckResponse> => {

  return customInstance<conflictCheckResponse>(getConflictCheckUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(conflictCheckRequest)
  }
);}





export const getConflictCheckMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conflictCheck>>, TError,{data: ConflictCheckRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof conflictCheck>>, TError,{data: ConflictCheckRequest}, TContext> => {

const mutationKey = ['conflictCheck'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof conflictCheck>>, {data: ConflictCheckRequest}> = (props) => {
          const {data} = props ?? {};

          return  conflictCheck(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConflictCheckMutationResult = NonNullable<Awaited<ReturnType<typeof conflictCheck>>>
    export type ConflictCheckMutationBody = ConflictCheckRequest
    export type ConflictCheckMutationError = HTTPValidationError

    /**
 * @summary Check Conflicts
 */
export const useConflictCheck = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof conflictCheck>>, TError,{data: ConflictCheckRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof conflictCheck>>,
        TError,
        {data: ConflictCheckRequest},
        TContext
      > => {
      return useMutation(getConflictCheckMutationOptions(options), queryClient);
    }
    export type overrideConflictResponse200 = {
  data: unknown
  status: 200
}

export type overrideConflictResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type overrideConflictResponseSuccess = (overrideConflictResponse200) & {
  headers: Headers;
};
export type overrideConflictResponseError = (overrideConflictResponse422) & {
  headers: Headers;
};

export type overrideConflictResponse = (overrideConflictResponseSuccess | overrideConflictResponseError)

export const getOverrideConflictUrl = (matterId: string,
    params?: OverrideConflictParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matters/${matterId}/override-conflict?${stringifiedParams}` : `/api/v1/matters/${matterId}/override-conflict`
}

/**
 * @summary Override Conflict
 */
export const overrideConflict = async (matterId: string,
    overrideConflictRequest: OverrideConflictRequest,
    params?: OverrideConflictParams, options?: RequestInit): Promise<overrideConflictResponse> => {

  return customInstance<overrideConflictResponse>(getOverrideConflictUrl(matterId,params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(overrideConflictRequest)
  }
);}





export const getOverrideConflictMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof overrideConflict>>, TError,{matterId: string;data: OverrideConflictRequest;params?: OverrideConflictParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof overrideConflict>>, TError,{matterId: string;data: OverrideConflictRequest;params?: OverrideConflictParams}, TContext> => {

const mutationKey = ['overrideConflict'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof overrideConflict>>, {matterId: string;data: OverrideConflictRequest;params?: OverrideConflictParams}> = (props) => {
          const {matterId,data,params} = props ?? {};

          return  overrideConflict(matterId,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OverrideConflictMutationResult = NonNullable<Awaited<ReturnType<typeof overrideConflict>>>
    export type OverrideConflictMutationBody = OverrideConflictRequest
    export type OverrideConflictMutationError = HTTPValidationError

    /**
 * @summary Override Conflict
 */
export const useOverrideConflict = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof overrideConflict>>, TError,{matterId: string;data: OverrideConflictRequest;params?: OverrideConflictParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof overrideConflict>>,
        TError,
        {matterId: string;data: OverrideConflictRequest;params?: OverrideConflictParams},
        TContext
      > => {
      return useMutation(getOverrideConflictMutationOptions(options), queryClient);
    }
    export type createUploadIntentResponse200 = {
  data: UploadIntentResponse
  status: 200
}

export type createUploadIntentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createUploadIntentResponseSuccess = (createUploadIntentResponse200) & {
  headers: Headers;
};
export type createUploadIntentResponseError = (createUploadIntentResponse422) & {
  headers: Headers;
};

export type createUploadIntentResponse = (createUploadIntentResponseSuccess | createUploadIntentResponseError)

export const getCreateUploadIntentUrl = () => {




  return `/api/v1/documents/upload-intent`
}

/**
 * @summary Create Upload Intent
 */
export const createUploadIntent = async (uploadIntentRequest: UploadIntentRequest, options?: RequestInit): Promise<createUploadIntentResponse> => {

  return customInstance<createUploadIntentResponse>(getCreateUploadIntentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(uploadIntentRequest)
  }
);}





export const getCreateUploadIntentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUploadIntent>>, TError,{data: UploadIntentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createUploadIntent>>, TError,{data: UploadIntentRequest}, TContext> => {

const mutationKey = ['createUploadIntent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUploadIntent>>, {data: UploadIntentRequest}> = (props) => {
          const {data} = props ?? {};

          return  createUploadIntent(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUploadIntentMutationResult = NonNullable<Awaited<ReturnType<typeof createUploadIntent>>>
    export type CreateUploadIntentMutationBody = UploadIntentRequest
    export type CreateUploadIntentMutationError = HTTPValidationError

    /**
 * @summary Create Upload Intent
 */
export const useCreateUploadIntent = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUploadIntent>>, TError,{data: UploadIntentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUploadIntent>>,
        TError,
        {data: UploadIntentRequest},
        TContext
      > => {
      return useMutation(getCreateUploadIntentMutationOptions(options), queryClient);
    }
    export type listMatterDocumentsResponse200 = {
  data: DocumentResponse[]
  status: 200
}

export type listMatterDocumentsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listMatterDocumentsResponseSuccess = (listMatterDocumentsResponse200) & {
  headers: Headers;
};
export type listMatterDocumentsResponseError = (listMatterDocumentsResponse422) & {
  headers: Headers;
};

export type listMatterDocumentsResponse = (listMatterDocumentsResponseSuccess | listMatterDocumentsResponseError)

export const getListMatterDocumentsUrl = (matterId: string,) => {




  return `/api/v1/documents/matters/${matterId}`
}

/**
 * @summary List Matter Documents
 */
export const listMatterDocuments = async (matterId: string, options?: RequestInit): Promise<listMatterDocumentsResponse> => {

  return customInstance<listMatterDocumentsResponse>(getListMatterDocumentsUrl(matterId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMatterDocumentsQueryKey = (matterId: string,) => {
    return [
    `/api/v1/documents/matters/${matterId}`
    ] as const;
    }


export const getListMatterDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof listMatterDocuments>>, TError = HTTPValidationError>(matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMatterDocumentsQueryKey(matterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMatterDocuments>>> = ({ signal }) => listMatterDocuments(matterId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: matterId !== null && matterId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMatterDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMatterDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listMatterDocuments>>>
export type ListMatterDocumentsQueryError = HTTPValidationError


export function useListMatterDocuments<TData = Awaited<ReturnType<typeof listMatterDocuments>>, TError = HTTPValidationError>(
 matterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatterDocuments>>,
          TError,
          Awaited<ReturnType<typeof listMatterDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatterDocuments<TData = Awaited<ReturnType<typeof listMatterDocuments>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatterDocuments>>,
          TError,
          Awaited<ReturnType<typeof listMatterDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatterDocuments<TData = Awaited<ReturnType<typeof listMatterDocuments>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Matter Documents
 */

export function useListMatterDocuments<TData = Awaited<ReturnType<typeof listMatterDocuments>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMatterDocumentsQueryOptions(matterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listAllDocumentsResponse200 = {
  data: DocumentResponse[]
  status: 200
}

export type listAllDocumentsResponseSuccess = (listAllDocumentsResponse200) & {
  headers: Headers;
};
;

export type listAllDocumentsResponse = (listAllDocumentsResponseSuccess)

export const getListAllDocumentsUrl = () => {




  return `/api/v1/documents`
}

/**
 * @summary List All Documents
 */
export const listAllDocuments = async ( options?: RequestInit): Promise<listAllDocumentsResponse> => {

  return customInstance<listAllDocumentsResponse>(getListAllDocumentsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAllDocumentsQueryKey = () => {
    return [
    `/api/v1/documents`
    ] as const;
    }


export const getListAllDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof listAllDocuments>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAllDocumentsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllDocuments>>> = ({ signal }) => listAllDocuments({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAllDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAllDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listAllDocuments>>>
export type ListAllDocumentsQueryError = unknown


export function useListAllDocuments<TData = Awaited<ReturnType<typeof listAllDocuments>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllDocuments>>,
          TError,
          Awaited<ReturnType<typeof listAllDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllDocuments<TData = Awaited<ReturnType<typeof listAllDocuments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllDocuments>>,
          TError,
          Awaited<ReturnType<typeof listAllDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllDocuments<TData = Awaited<ReturnType<typeof listAllDocuments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List All Documents
 */

export function useListAllDocuments<TData = Awaited<ReturnType<typeof listAllDocuments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAllDocumentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getDocumentResponse200 = {
  data: DocumentResponse
  status: 200
}

export type getDocumentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getDocumentResponseSuccess = (getDocumentResponse200) & {
  headers: Headers;
};
export type getDocumentResponseError = (getDocumentResponse422) & {
  headers: Headers;
};

export type getDocumentResponse = (getDocumentResponseSuccess | getDocumentResponseError)

export const getGetDocumentUrl = (documentId: string,) => {




  return `/api/v1/documents/${documentId}`
}

/**
 * @summary Get Document
 */
export const getDocument = async (documentId: string, options?: RequestInit): Promise<getDocumentResponse> => {

  return customInstance<getDocumentResponse>(getGetDocumentUrl(documentId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDocumentQueryKey = (documentId: string,) => {
    return [
    `/api/v1/documents/${documentId}`
    ] as const;
    }


export const getGetDocumentQueryOptions = <TData = Awaited<ReturnType<typeof getDocument>>, TError = HTTPValidationError>(documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentQueryKey(documentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocument>>> = ({ signal }) => getDocument(documentId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: documentId !== null && documentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof getDocument>>>
export type GetDocumentQueryError = HTTPValidationError


export function useGetDocument<TData = Awaited<ReturnType<typeof getDocument>>, TError = HTTPValidationError>(
 documentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocument>>,
          TError,
          Awaited<ReturnType<typeof getDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocument<TData = Awaited<ReturnType<typeof getDocument>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocument>>,
          TError,
          Awaited<ReturnType<typeof getDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocument<TData = Awaited<ReturnType<typeof getDocument>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document
 */

export function useGetDocument<TData = Awaited<ReturnType<typeof getDocument>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type completeUploadResponse200 = {
  data: unknown
  status: 200
}

export type completeUploadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type completeUploadResponseSuccess = (completeUploadResponse200) & {
  headers: Headers;
};
export type completeUploadResponseError = (completeUploadResponse422) & {
  headers: Headers;
};

export type completeUploadResponse = (completeUploadResponseSuccess | completeUploadResponseError)

export const getCompleteUploadUrl = (documentId: string,) => {




  return `/api/v1/documents/${documentId}/complete`
}

/**
 * @summary Complete Upload
 */
export const completeUpload = async (documentId: string, options?: RequestInit): Promise<completeUploadResponse> => {

  return customInstance<completeUploadResponse>(getCompleteUploadUrl(documentId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCompleteUploadMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeUpload>>, TError,{documentId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof completeUpload>>, TError,{documentId: string}, TContext> => {

const mutationKey = ['completeUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeUpload>>, {documentId: string}> = (props) => {
          const {documentId} = props ?? {};

          return  completeUpload(documentId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteUploadMutationResult = NonNullable<Awaited<ReturnType<typeof completeUpload>>>

    export type CompleteUploadMutationError = HTTPValidationError

    /**
 * @summary Complete Upload
 */
export const useCompleteUpload = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeUpload>>, TError,{documentId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeUpload>>,
        TError,
        {documentId: string},
        TContext
      > => {
      return useMutation(getCompleteUploadMutationOptions(options), queryClient);
    }
    export type downloadDocumentResponse200 = {
  data: unknown
  status: 200
}

export type downloadDocumentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type downloadDocumentResponseSuccess = (downloadDocumentResponse200) & {
  headers: Headers;
};
export type downloadDocumentResponseError = (downloadDocumentResponse422) & {
  headers: Headers;
};

export type downloadDocumentResponse = (downloadDocumentResponseSuccess | downloadDocumentResponseError)

export const getDownloadDocumentUrl = (documentId: string,) => {




  return `/api/v1/documents/${documentId}/download`
}

/**
 * @summary Download Document
 */
export const downloadDocument = async (documentId: string, options?: RequestInit): Promise<downloadDocumentResponse> => {

  return customInstance<downloadDocumentResponse>(getDownloadDocumentUrl(documentId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDownloadDocumentQueryKey = (documentId: string,) => {
    return [
    `/api/v1/documents/${documentId}/download`
    ] as const;
    }


export const getDownloadDocumentQueryOptions = <TData = Awaited<ReturnType<typeof downloadDocument>>, TError = HTTPValidationError>(documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadDocument>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadDocumentQueryKey(documentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadDocument>>> = ({ signal }) => downloadDocument(documentId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: documentId !== null && documentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadDocument>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof downloadDocument>>>
export type DownloadDocumentQueryError = HTTPValidationError


export function useDownloadDocument<TData = Awaited<ReturnType<typeof downloadDocument>>, TError = HTTPValidationError>(
 documentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadDocument>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadDocument>>,
          TError,
          Awaited<ReturnType<typeof downloadDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadDocument<TData = Awaited<ReturnType<typeof downloadDocument>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadDocument>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadDocument>>,
          TError,
          Awaited<ReturnType<typeof downloadDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadDocument<TData = Awaited<ReturnType<typeof downloadDocument>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadDocument>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Document
 */

export function useDownloadDocument<TData = Awaited<ReturnType<typeof downloadDocument>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadDocument>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadDocumentQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listMatterPartiesResponse200 = {
  data: unknown
  status: 200
}

export type listMatterPartiesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listMatterPartiesResponseSuccess = (listMatterPartiesResponse200) & {
  headers: Headers;
};
export type listMatterPartiesResponseError = (listMatterPartiesResponse422) & {
  headers: Headers;
};

export type listMatterPartiesResponse = (listMatterPartiesResponseSuccess | listMatterPartiesResponseError)

export const getListMatterPartiesUrl = (matterId: string,) => {




  return `/api/v1/matters/${matterId}/parties`
}

/**
 * @summary List Matter Parties
 */
export const listMatterParties = async (matterId: string, options?: RequestInit): Promise<listMatterPartiesResponse> => {

  return customInstance<listMatterPartiesResponse>(getListMatterPartiesUrl(matterId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMatterPartiesQueryKey = (matterId: string,) => {
    return [
    `/api/v1/matters/${matterId}/parties`
    ] as const;
    }


export const getListMatterPartiesQueryOptions = <TData = Awaited<ReturnType<typeof listMatterParties>>, TError = HTTPValidationError>(matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterParties>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMatterPartiesQueryKey(matterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMatterParties>>> = ({ signal }) => listMatterParties(matterId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: matterId !== null && matterId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMatterParties>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMatterPartiesQueryResult = NonNullable<Awaited<ReturnType<typeof listMatterParties>>>
export type ListMatterPartiesQueryError = HTTPValidationError


export function useListMatterParties<TData = Awaited<ReturnType<typeof listMatterParties>>, TError = HTTPValidationError>(
 matterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterParties>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatterParties>>,
          TError,
          Awaited<ReturnType<typeof listMatterParties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatterParties<TData = Awaited<ReturnType<typeof listMatterParties>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterParties>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatterParties>>,
          TError,
          Awaited<ReturnType<typeof listMatterParties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatterParties<TData = Awaited<ReturnType<typeof listMatterParties>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterParties>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Matter Parties
 */

export function useListMatterParties<TData = Awaited<ReturnType<typeof listMatterParties>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterParties>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMatterPartiesQueryOptions(matterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listClaimsResponse200 = {
  data: unknown
  status: 200
}

export type listClaimsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listClaimsResponseSuccess = (listClaimsResponse200) & {
  headers: Headers;
};
export type listClaimsResponseError = (listClaimsResponse422) & {
  headers: Headers;
};

export type listClaimsResponse = (listClaimsResponseSuccess | listClaimsResponseError)

export const getListClaimsUrl = (matterId: string,) => {




  return `/api/v1/matters/${matterId}/claims`
}

/**
 * @summary List Claims
 */
export const listClaims = async (matterId: string, options?: RequestInit): Promise<listClaimsResponse> => {

  return customInstance<listClaimsResponse>(getListClaimsUrl(matterId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListClaimsQueryKey = (matterId: string,) => {
    return [
    `/api/v1/matters/${matterId}/claims`
    ] as const;
    }


export const getListClaimsQueryOptions = <TData = Awaited<ReturnType<typeof listClaims>>, TError = HTTPValidationError>(matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaims>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListClaimsQueryKey(matterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listClaims>>> = ({ signal }) => listClaims(matterId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: matterId !== null && matterId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listClaims>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListClaimsQueryResult = NonNullable<Awaited<ReturnType<typeof listClaims>>>
export type ListClaimsQueryError = HTTPValidationError


export function useListClaims<TData = Awaited<ReturnType<typeof listClaims>>, TError = HTTPValidationError>(
 matterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaims>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClaims>>,
          TError,
          Awaited<ReturnType<typeof listClaims>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListClaims<TData = Awaited<ReturnType<typeof listClaims>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaims>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClaims>>,
          TError,
          Awaited<ReturnType<typeof listClaims>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListClaims<TData = Awaited<ReturnType<typeof listClaims>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaims>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Claims
 */

export function useListClaims<TData = Awaited<ReturnType<typeof listClaims>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaims>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListClaimsQueryOptions(matterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listEvidenceResponse200 = {
  data: unknown
  status: 200
}

export type listEvidenceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listEvidenceResponseSuccess = (listEvidenceResponse200) & {
  headers: Headers;
};
export type listEvidenceResponseError = (listEvidenceResponse422) & {
  headers: Headers;
};

export type listEvidenceResponse = (listEvidenceResponseSuccess | listEvidenceResponseError)

export const getListEvidenceUrl = (matterId: string,) => {




  return `/api/v1/matters/${matterId}/evidence`
}

/**
 * @summary List Evidence
 */
export const listEvidence = async (matterId: string, options?: RequestInit): Promise<listEvidenceResponse> => {

  return customInstance<listEvidenceResponse>(getListEvidenceUrl(matterId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEvidenceQueryKey = (matterId: string,) => {
    return [
    `/api/v1/matters/${matterId}/evidence`
    ] as const;
    }


export const getListEvidenceQueryOptions = <TData = Awaited<ReturnType<typeof listEvidence>>, TError = HTTPValidationError>(matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidence>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEvidenceQueryKey(matterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEvidence>>> = ({ signal }) => listEvidence(matterId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: matterId !== null && matterId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEvidence>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEvidenceQueryResult = NonNullable<Awaited<ReturnType<typeof listEvidence>>>
export type ListEvidenceQueryError = HTTPValidationError


export function useListEvidence<TData = Awaited<ReturnType<typeof listEvidence>>, TError = HTTPValidationError>(
 matterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidence>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEvidence>>,
          TError,
          Awaited<ReturnType<typeof listEvidence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEvidence<TData = Awaited<ReturnType<typeof listEvidence>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidence>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEvidence>>,
          TError,
          Awaited<ReturnType<typeof listEvidence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEvidence<TData = Awaited<ReturnType<typeof listEvidence>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidence>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Evidence
 */

export function useListEvidence<TData = Awaited<ReturnType<typeof listEvidence>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidence>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEvidenceQueryOptions(matterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listTimelineEventsResponse200 = {
  data: unknown
  status: 200
}

export type listTimelineEventsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listTimelineEventsResponseSuccess = (listTimelineEventsResponse200) & {
  headers: Headers;
};
export type listTimelineEventsResponseError = (listTimelineEventsResponse422) & {
  headers: Headers;
};

export type listTimelineEventsResponse = (listTimelineEventsResponseSuccess | listTimelineEventsResponseError)

export const getListTimelineEventsUrl = (matterId: string,) => {




  return `/api/v1/matters/${matterId}/timeline`
}

/**
 * @summary List Timeline Events
 */
export const listTimelineEvents = async (matterId: string, options?: RequestInit): Promise<listTimelineEventsResponse> => {

  return customInstance<listTimelineEventsResponse>(getListTimelineEventsUrl(matterId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTimelineEventsQueryKey = (matterId: string,) => {
    return [
    `/api/v1/matters/${matterId}/timeline`
    ] as const;
    }


export const getListTimelineEventsQueryOptions = <TData = Awaited<ReturnType<typeof listTimelineEvents>>, TError = HTTPValidationError>(matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimelineEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTimelineEventsQueryKey(matterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTimelineEvents>>> = ({ signal }) => listTimelineEvents(matterId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: matterId !== null && matterId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTimelineEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTimelineEventsQueryResult = NonNullable<Awaited<ReturnType<typeof listTimelineEvents>>>
export type ListTimelineEventsQueryError = HTTPValidationError


export function useListTimelineEvents<TData = Awaited<ReturnType<typeof listTimelineEvents>>, TError = HTTPValidationError>(
 matterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimelineEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTimelineEvents>>,
          TError,
          Awaited<ReturnType<typeof listTimelineEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTimelineEvents<TData = Awaited<ReturnType<typeof listTimelineEvents>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimelineEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTimelineEvents>>,
          TError,
          Awaited<ReturnType<typeof listTimelineEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTimelineEvents<TData = Awaited<ReturnType<typeof listTimelineEvents>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimelineEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Timeline Events
 */

export function useListTimelineEvents<TData = Awaited<ReturnType<typeof listTimelineEvents>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimelineEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTimelineEventsQueryOptions(matterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listClaimsWithEvidenceResponse200 = {
  data: unknown
  status: 200
}

export type listClaimsWithEvidenceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listClaimsWithEvidenceResponseSuccess = (listClaimsWithEvidenceResponse200) & {
  headers: Headers;
};
export type listClaimsWithEvidenceResponseError = (listClaimsWithEvidenceResponse422) & {
  headers: Headers;
};

export type listClaimsWithEvidenceResponse = (listClaimsWithEvidenceResponseSuccess | listClaimsWithEvidenceResponseError)

export const getListClaimsWithEvidenceUrl = (matterId: string,) => {




  return `/api/v1/matters/${matterId}/claims-evidence`
}

/**
 * @summary List Claims With Evidence
 */
export const listClaimsWithEvidence = async (matterId: string, options?: RequestInit): Promise<listClaimsWithEvidenceResponse> => {

  return customInstance<listClaimsWithEvidenceResponse>(getListClaimsWithEvidenceUrl(matterId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListClaimsWithEvidenceQueryKey = (matterId: string,) => {
    return [
    `/api/v1/matters/${matterId}/claims-evidence`
    ] as const;
    }


export const getListClaimsWithEvidenceQueryOptions = <TData = Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError = HTTPValidationError>(matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListClaimsWithEvidenceQueryKey(matterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listClaimsWithEvidence>>> = ({ signal }) => listClaimsWithEvidence(matterId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: matterId !== null && matterId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListClaimsWithEvidenceQueryResult = NonNullable<Awaited<ReturnType<typeof listClaimsWithEvidence>>>
export type ListClaimsWithEvidenceQueryError = HTTPValidationError


export function useListClaimsWithEvidence<TData = Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError = HTTPValidationError>(
 matterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClaimsWithEvidence>>,
          TError,
          Awaited<ReturnType<typeof listClaimsWithEvidence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListClaimsWithEvidence<TData = Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClaimsWithEvidence>>,
          TError,
          Awaited<ReturnType<typeof listClaimsWithEvidence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListClaimsWithEvidence<TData = Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Claims With Evidence
 */

export function useListClaimsWithEvidence<TData = Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError = HTTPValidationError>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaimsWithEvidence>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListClaimsWithEvidenceQueryOptions(matterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listParsedDocumentsResponse200 = {
  data: ParsedDocumentResponse[]
  status: 200
}

export type listParsedDocumentsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listParsedDocumentsResponseSuccess = (listParsedDocumentsResponse200) & {
  headers: Headers;
};
export type listParsedDocumentsResponseError = (listParsedDocumentsResponse422) & {
  headers: Headers;
};

export type listParsedDocumentsResponse = (listParsedDocumentsResponseSuccess | listParsedDocumentsResponseError)

export const getListParsedDocumentsUrl = (documentId: string,) => {




  return `/api/v1/parser/document/${documentId}`
}

/**
 * @summary List Parsed Documents
 */
export const listParsedDocuments = async (documentId: string, options?: RequestInit): Promise<listParsedDocumentsResponse> => {

  return customInstance<listParsedDocumentsResponse>(getListParsedDocumentsUrl(documentId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListParsedDocumentsQueryKey = (documentId: string,) => {
    return [
    `/api/v1/parser/document/${documentId}`
    ] as const;
    }


export const getListParsedDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof listParsedDocuments>>, TError = HTTPValidationError>(documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListParsedDocumentsQueryKey(documentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listParsedDocuments>>> = ({ signal }) => listParsedDocuments(documentId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: documentId !== null && documentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listParsedDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListParsedDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listParsedDocuments>>>
export type ListParsedDocumentsQueryError = HTTPValidationError


export function useListParsedDocuments<TData = Awaited<ReturnType<typeof listParsedDocuments>>, TError = HTTPValidationError>(
 documentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listParsedDocuments>>,
          TError,
          Awaited<ReturnType<typeof listParsedDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListParsedDocuments<TData = Awaited<ReturnType<typeof listParsedDocuments>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listParsedDocuments>>,
          TError,
          Awaited<ReturnType<typeof listParsedDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListParsedDocuments<TData = Awaited<ReturnType<typeof listParsedDocuments>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Parsed Documents
 */

export function useListParsedDocuments<TData = Awaited<ReturnType<typeof listParsedDocuments>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedDocuments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListParsedDocumentsQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listParsedPagesResponse200 = {
  data: ParsedPageResponse[]
  status: 200
}

export type listParsedPagesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listParsedPagesResponseSuccess = (listParsedPagesResponse200) & {
  headers: Headers;
};
export type listParsedPagesResponseError = (listParsedPagesResponse422) & {
  headers: Headers;
};

export type listParsedPagesResponse = (listParsedPagesResponseSuccess | listParsedPagesResponseError)

export const getListParsedPagesUrl = (parsedDocumentId: string,) => {




  return `/api/v1/parser/${parsedDocumentId}/pages`
}

/**
 * @summary List Parsed Pages
 */
export const listParsedPages = async (parsedDocumentId: string, options?: RequestInit): Promise<listParsedPagesResponse> => {

  return customInstance<listParsedPagesResponse>(getListParsedPagesUrl(parsedDocumentId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListParsedPagesQueryKey = (parsedDocumentId: string,) => {
    return [
    `/api/v1/parser/${parsedDocumentId}/pages`
    ] as const;
    }


export const getListParsedPagesQueryOptions = <TData = Awaited<ReturnType<typeof listParsedPages>>, TError = HTTPValidationError>(parsedDocumentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedPages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListParsedPagesQueryKey(parsedDocumentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listParsedPages>>> = ({ signal }) => listParsedPages(parsedDocumentId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: parsedDocumentId !== null && parsedDocumentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listParsedPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListParsedPagesQueryResult = NonNullable<Awaited<ReturnType<typeof listParsedPages>>>
export type ListParsedPagesQueryError = HTTPValidationError


export function useListParsedPages<TData = Awaited<ReturnType<typeof listParsedPages>>, TError = HTTPValidationError>(
 parsedDocumentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listParsedPages>>,
          TError,
          Awaited<ReturnType<typeof listParsedPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListParsedPages<TData = Awaited<ReturnType<typeof listParsedPages>>, TError = HTTPValidationError>(
 parsedDocumentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listParsedPages>>,
          TError,
          Awaited<ReturnType<typeof listParsedPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListParsedPages<TData = Awaited<ReturnType<typeof listParsedPages>>, TError = HTTPValidationError>(
 parsedDocumentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedPages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Parsed Pages
 */

export function useListParsedPages<TData = Awaited<ReturnType<typeof listParsedPages>>, TError = HTTPValidationError>(
 parsedDocumentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParsedPages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListParsedPagesQueryOptions(parsedDocumentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






