/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MESA Law API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApproveDraftParams,
  DraftCitationResponse,
  DraftDetailResponse,
  DraftStatusResponse,
  DraftSummaryResponse,
  ExportDraftRequest,
  ExportDraftResponse,
  GenerateDraftRequest,
  GenerateDraftResponse,
  HTTPValidationError,
  SaveDraftRequest,
  UpdateDraftRequest
} from '../../models';

import { customInstance } from '../../../lib/api/client';
import type { ErrorType , BodyType } from '../../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List All Drafts
 */
export const listAllDrafts = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DraftSummaryResponse[]>(
      {url: `/api/v1/draft-studio/drafts`, method: 'GET', signal
    },
      options);
    }




export const getListAllDraftsQueryKey = () => {
    return [
    `/api/v1/draft-studio/drafts`
    ] as const;
    }


export const getListAllDraftsQueryOptions = <TData = Awaited<ReturnType<typeof listAllDrafts>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAllDraftsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllDrafts>>> = ({ signal }) => listAllDrafts(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAllDrafts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAllDraftsQueryResult = NonNullable<Awaited<ReturnType<typeof listAllDrafts>>>
export type ListAllDraftsQueryError = ErrorType<unknown>


export function useListAllDrafts<TData = Awaited<ReturnType<typeof listAllDrafts>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDrafts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllDrafts>>,
          TError,
          Awaited<ReturnType<typeof listAllDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllDrafts<TData = Awaited<ReturnType<typeof listAllDrafts>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDrafts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllDrafts>>,
          TError,
          Awaited<ReturnType<typeof listAllDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllDrafts<TData = Awaited<ReturnType<typeof listAllDrafts>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List All Drafts
 */

export function useListAllDrafts<TData = Awaited<ReturnType<typeof listAllDrafts>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAllDraftsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Save Draft
 */
export const saveDraft = (
    saveDraftRequest: BodyType<SaveDraftRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DraftDetailResponse>(
      {url: `/api/v1/draft-studio/drafts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saveDraftRequest, signal
    },
      options);
    }




export const getSaveDraftMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveDraft>>, TError,{data: BodyType<SaveDraftRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saveDraft>>, TError,{data: BodyType<SaveDraftRequest>}, TContext> => {

const mutationKey = ['saveDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveDraft>>, {data: BodyType<SaveDraftRequest>}> = (props) => {
          const {data} = props ?? {};

          return  saveDraft(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaveDraftMutationResult = NonNullable<Awaited<ReturnType<typeof saveDraft>>>
    export type SaveDraftMutationBody = BodyType<SaveDraftRequest>
    export type SaveDraftMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Save Draft
 */
export const useSaveDraft = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveDraft>>, TError,{data: BodyType<SaveDraftRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveDraft>>,
        TError,
        {data: BodyType<SaveDraftRequest>},
        TContext
      > => {
      return useMutation(getSaveDraftMutationOptions(options), queryClient);
    }
    /**
 * @summary Generate Draft
 */
export const generateDraft = (
    generateDraftRequest: BodyType<GenerateDraftRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GenerateDraftResponse>(
      {url: `/api/v1/draft-studio/drafts/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateDraftRequest, signal
    },
      options);
    }




export const getGenerateDraftMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateDraft>>, TError,{data: BodyType<GenerateDraftRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof generateDraft>>, TError,{data: BodyType<GenerateDraftRequest>}, TContext> => {

const mutationKey = ['generateDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateDraft>>, {data: BodyType<GenerateDraftRequest>}> = (props) => {
          const {data} = props ?? {};

          return  generateDraft(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GenerateDraftMutationResult = NonNullable<Awaited<ReturnType<typeof generateDraft>>>
    export type GenerateDraftMutationBody = BodyType<GenerateDraftRequest>
    export type GenerateDraftMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Generate Draft
 */
export const useGenerateDraft = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateDraft>>, TError,{data: BodyType<GenerateDraftRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateDraft>>,
        TError,
        {data: BodyType<GenerateDraftRequest>},
        TContext
      > => {
      return useMutation(getGenerateDraftMutationOptions(options), queryClient);
    }
    /**
 * @summary List Matter Drafts
 */
export const listMatterDrafts = (
    matterId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DraftSummaryResponse[]>(
      {url: `/api/v1/draft-studio/drafts/matter/${matterId}`, method: 'GET', signal
    },
      options);
    }




export const getListMatterDraftsQueryKey = (matterId: string,) => {
    return [
    `/api/v1/draft-studio/drafts/matter/${matterId}`
    ] as const;
    }


export const getListMatterDraftsQueryOptions = <TData = Awaited<ReturnType<typeof listMatterDrafts>>, TError = ErrorType<HTTPValidationError>>(matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMatterDraftsQueryKey(matterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMatterDrafts>>> = ({ signal }) => listMatterDrafts(matterId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: matterId !== null && matterId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMatterDrafts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMatterDraftsQueryResult = NonNullable<Awaited<ReturnType<typeof listMatterDrafts>>>
export type ListMatterDraftsQueryError = ErrorType<HTTPValidationError>


export function useListMatterDrafts<TData = Awaited<ReturnType<typeof listMatterDrafts>>, TError = ErrorType<HTTPValidationError>>(
 matterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDrafts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatterDrafts>>,
          TError,
          Awaited<ReturnType<typeof listMatterDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatterDrafts<TData = Awaited<ReturnType<typeof listMatterDrafts>>, TError = ErrorType<HTTPValidationError>>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDrafts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatterDrafts>>,
          TError,
          Awaited<ReturnType<typeof listMatterDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatterDrafts<TData = Awaited<ReturnType<typeof listMatterDrafts>>, TError = ErrorType<HTTPValidationError>>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Matter Drafts
 */

export function useListMatterDrafts<TData = Awaited<ReturnType<typeof listMatterDrafts>>, TError = ErrorType<HTTPValidationError>>(
 matterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatterDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMatterDraftsQueryOptions(matterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Get Draft
 */
export const getDraft = (
    draftId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DraftDetailResponse>(
      {url: `/api/v1/draft-studio/drafts/${draftId}`, method: 'GET', signal
    },
      options);
    }




export const getGetDraftQueryKey = (draftId: string,) => {
    return [
    `/api/v1/draft-studio/drafts/${draftId}`
    ] as const;
    }


export const getGetDraftQueryOptions = <TData = Awaited<ReturnType<typeof getDraft>>, TError = ErrorType<HTTPValidationError>>(draftId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraft>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDraftQueryKey(draftId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDraft>>> = ({ signal }) => getDraft(draftId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: draftId !== null && draftId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDraft>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDraftQueryResult = NonNullable<Awaited<ReturnType<typeof getDraft>>>
export type GetDraftQueryError = ErrorType<HTTPValidationError>


export function useGetDraft<TData = Awaited<ReturnType<typeof getDraft>>, TError = ErrorType<HTTPValidationError>>(
 draftId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraft>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDraft>>,
          TError,
          Awaited<ReturnType<typeof getDraft>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDraft<TData = Awaited<ReturnType<typeof getDraft>>, TError = ErrorType<HTTPValidationError>>(
 draftId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraft>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDraft>>,
          TError,
          Awaited<ReturnType<typeof getDraft>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDraft<TData = Awaited<ReturnType<typeof getDraft>>, TError = ErrorType<HTTPValidationError>>(
 draftId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraft>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Draft
 */

export function useGetDraft<TData = Awaited<ReturnType<typeof getDraft>>, TError = ErrorType<HTTPValidationError>>(
 draftId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraft>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDraftQueryOptions(draftId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Update Draft
 */
export const updateDraft = (
    draftId: string,
    updateDraftRequest: BodyType<UpdateDraftRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DraftDetailResponse>(
      {url: `/api/v1/draft-studio/drafts/${draftId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateDraftRequest, signal
    },
      options);
    }




export const getUpdateDraftMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDraft>>, TError,{draftId: string;data: BodyType<UpdateDraftRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDraft>>, TError,{draftId: string;data: BodyType<UpdateDraftRequest>}, TContext> => {

const mutationKey = ['updateDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDraft>>, {draftId: string;data: BodyType<UpdateDraftRequest>}> = (props) => {
          const {draftId,data} = props ?? {};

          return  updateDraft(draftId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDraftMutationResult = NonNullable<Awaited<ReturnType<typeof updateDraft>>>
    export type UpdateDraftMutationBody = BodyType<UpdateDraftRequest>
    export type UpdateDraftMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Draft
 */
export const useUpdateDraft = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDraft>>, TError,{draftId: string;data: BodyType<UpdateDraftRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDraft>>,
        TError,
        {draftId: string;data: BodyType<UpdateDraftRequest>},
        TContext
      > => {
      return useMutation(getUpdateDraftMutationOptions(options), queryClient);
    }
    /**
 * @summary Approve Draft
 */
export const approveDraft = (
    draftId: string,
    params?: ApproveDraftParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DraftStatusResponse>(
      {url: `/api/v1/draft-studio/drafts/${draftId}/approve`, method: 'POST',
        params, signal
    },
      options);
    }




export const getApproveDraftMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveDraft>>, TError,{draftId: string;params?: ApproveDraftParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof approveDraft>>, TError,{draftId: string;params?: ApproveDraftParams}, TContext> => {

const mutationKey = ['approveDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveDraft>>, {draftId: string;params?: ApproveDraftParams}> = (props) => {
          const {draftId,params} = props ?? {};

          return  approveDraft(draftId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApproveDraftMutationResult = NonNullable<Awaited<ReturnType<typeof approveDraft>>>

    export type ApproveDraftMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Approve Draft
 */
export const useApproveDraft = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveDraft>>, TError,{draftId: string;params?: ApproveDraftParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approveDraft>>,
        TError,
        {draftId: string;params?: ApproveDraftParams},
        TContext
      > => {
      return useMutation(getApproveDraftMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Draft Citations
 */
export const getDraftCitations = (
    draftId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DraftCitationResponse[]>(
      {url: `/api/v1/draft-studio/drafts/${draftId}/citations`, method: 'GET', signal
    },
      options);
    }




export const getGetDraftCitationsQueryKey = (draftId: string,) => {
    return [
    `/api/v1/draft-studio/drafts/${draftId}/citations`
    ] as const;
    }


export const getGetDraftCitationsQueryOptions = <TData = Awaited<ReturnType<typeof getDraftCitations>>, TError = ErrorType<HTTPValidationError>>(draftId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraftCitations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDraftCitationsQueryKey(draftId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDraftCitations>>> = ({ signal }) => getDraftCitations(draftId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: draftId !== null && draftId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDraftCitations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDraftCitationsQueryResult = NonNullable<Awaited<ReturnType<typeof getDraftCitations>>>
export type GetDraftCitationsQueryError = ErrorType<HTTPValidationError>


export function useGetDraftCitations<TData = Awaited<ReturnType<typeof getDraftCitations>>, TError = ErrorType<HTTPValidationError>>(
 draftId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraftCitations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDraftCitations>>,
          TError,
          Awaited<ReturnType<typeof getDraftCitations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDraftCitations<TData = Awaited<ReturnType<typeof getDraftCitations>>, TError = ErrorType<HTTPValidationError>>(
 draftId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraftCitations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDraftCitations>>,
          TError,
          Awaited<ReturnType<typeof getDraftCitations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDraftCitations<TData = Awaited<ReturnType<typeof getDraftCitations>>, TError = ErrorType<HTTPValidationError>>(
 draftId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraftCitations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Draft Citations
 */

export function useGetDraftCitations<TData = Awaited<ReturnType<typeof getDraftCitations>>, TError = ErrorType<HTTPValidationError>>(
 draftId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDraftCitations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDraftCitationsQueryOptions(draftId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Export Draft
 */
export const exportDraft = (
    draftId: string,
    exportDraftRequest: BodyType<ExportDraftRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ExportDraftResponse>(
      {url: `/api/v1/draft-studio/drafts/${draftId}/export`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportDraftRequest, signal
    },
      options);
    }




export const getExportDraftMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportDraft>>, TError,{draftId: string;data: BodyType<ExportDraftRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof exportDraft>>, TError,{draftId: string;data: BodyType<ExportDraftRequest>}, TContext> => {

const mutationKey = ['exportDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exportDraft>>, {draftId: string;data: BodyType<ExportDraftRequest>}> = (props) => {
          const {draftId,data} = props ?? {};

          return  exportDraft(draftId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExportDraftMutationResult = NonNullable<Awaited<ReturnType<typeof exportDraft>>>
    export type ExportDraftMutationBody = BodyType<ExportDraftRequest>
    export type ExportDraftMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Export Draft
 */
export const useExportDraft = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportDraft>>, TError,{draftId: string;data: BodyType<ExportDraftRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exportDraft>>,
        TError,
        {draftId: string;data: BodyType<ExportDraftRequest>},
        TContext
      > => {
      return useMutation(getExportDraftMutationOptions(options), queryClient);
    }
    /**
 * @summary Submit Review Draft
 */
export const submitReviewDraft = (
    draftId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DraftStatusResponse>(
      {url: `/api/v1/draft-studio/drafts/${draftId}/submit-review`, method: 'POST', signal
    },
      options);
    }




export const getSubmitReviewDraftMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitReviewDraft>>, TError,{draftId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof submitReviewDraft>>, TError,{draftId: string}, TContext> => {

const mutationKey = ['submitReviewDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitReviewDraft>>, {draftId: string}> = (props) => {
          const {draftId} = props ?? {};

          return  submitReviewDraft(draftId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubmitReviewDraftMutationResult = NonNullable<Awaited<ReturnType<typeof submitReviewDraft>>>

    export type SubmitReviewDraftMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Submit Review Draft
 */
export const useSubmitReviewDraft = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitReviewDraft>>, TError,{draftId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitReviewDraft>>,
        TError,
        {draftId: string},
        TContext
      > => {
      return useMutation(getSubmitReviewDraftMutationOptions(options), queryClient);
    }
